/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2017-03-16 17:58:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class house_005fwork_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <title>Connecting the Unconnected Website | house work data :: On Going Solution</title>\n");
      out.write("\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("        <meta name=\"keywords\" content=\"Connecting the Unconnected Services website, Bootstrap css spring MVC hibernate web project owner by wprameethmadusanka@gmail.com.\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- //custom-theme -->\n");
      out.write("        <link href=\"buyer/assets/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"buyer/assets/css/style_new.css\" rel=\"stylesheet\" type=\"text/css\"/>                \n");
      out.write("        <!-- js -->\n");
      out.write("        <script src=\"buyer/assets/js/jquery-2.1.4.min.js\" type=\"text/javascript\"></script>             \n");
      out.write("        <!-- //js -->\n");
      out.write("        <link href=\"buyer/assets/css/flexslider.css\" rel=\"stylesheet\" type=\"text/css\"/>              \n");
      out.write("\n");
      out.write("        <!-- font-awesome-icons -->\n");
      out.write("        <link href=\"buyer/assets/css/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\"/>              \n");
      out.write("        <!-- //font-awesome-icons -->\n");
      out.write("        <link href=\"http://fonts.googleapis.com/css?family=Prompt:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext,thai,vietnamese\" rel=\"stylesheet\">\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <!--1.10.2-->\n");
      out.write("        <script src=\"buyer/assets/js/jquery.min.js\" type=\"text/javascript\"></script>        \n");
      out.write("        <script>\n");
      out.write("            (function (i, s, o, g, r, a, m) {\n");
      out.write("                i['GoogleAnalyticsObject'] = r;\n");
      out.write("                i[r] = i[r] || function () {\n");
      out.write("                    (i[r].q = i[r].q || []).push(arguments);\n");
      out.write("                }, i[r].l = 1 * new Date();\n");
      out.write("                a = s.createElement(o),\n");
      out.write("                        m = s.getElementsByTagName(o)[0];\n");
      out.write("                a.async = 1;\n");
      out.write("                a.src = g;\n");
      out.write("                m.parentNode.insertBefore(a, m);\n");
      out.write("            })(window, document, 'script', 'buyer/assets/js/analytics.js', 'ga');\n");
      out.write("            ga('create', 'UA-30027142-1', 'w3layouts.com');\n");
      out.write("            ga('send', 'pageview');\n");
      out.write("        </script>\n");
      out.write("        <script async type='text/javascript' src='buyer/assets/js/fancybar6a2f.js?zoneid=1502&amp;serve=C6ADVKE&amp;placement=w3layouts' id='_fancybar_js'></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- banner -->\n");
      out.write("        <div class=\"banner\">\n");
      out.write("            <nav class=\"navbar navbar-default\">\n");
      out.write("                <div class=\"navbar-header navbar-left\">\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                    </button>\n");
      out.write("                    <h1><a class=\"navbar-brand\" href=\"index.html\"><span>My</span>hero</a></h1>\n");
      out.write("                </div>\n");
      out.write("                <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("                <div class=\"collapse navbar-collapse navbar-right\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("                    <nav class=\"link-effect-2\" id=\"link-effect-2\">\n");
      out.write("                        <ul class=\"nav navbar-nav\">\n");
      out.write("                            <li class=\"active\"><a href=\"index.html\"><span data-hover=\"Home\">Home</span></a></li>                            \n");
      out.write("                            <li><a href=\"services.html\"><span data-hover=\"Services\">Services</span></a></li>  \n");
      out.write("                            <li><a href=\"services.html\"><span data-hover=\"Services\">About Us</span></a></li>   \n");
      out.write("                            <li><a href=\"mail.html\"><span data-hover=\"Mail Us\">Sign In</span></a></li>\n");
      out.write("                            <li><a href=\"services.html\"><span data-hover=\"Services\">Sign Up</span></a></li>  \n");
      out.write("                            <li><a href=\"services.html\"><span data-hover=\"Services\">සිංහල </span></a></li>   \n");
      out.write("                        </ul>\n");
      out.write("                    </nav>\n");
      out.write("                </div>                \n");
      out.write("            </nav>\n");
      out.write("            <div class=\"container\">    \n");
      out.write("                <br><br>\n");
      out.write("                <section class=\"tm-welcome-section\" style=\"text-align: center\">\n");
      out.write("                    <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\" >\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"container tm-position-relative\">\n");
      out.write("                        <div class=\"jobak-home-search-box\">\n");
      out.write("                            <form method=\"post\" action=\"buyer_second.jsp\" id=\"myForm\">\n");
      out.write("                                <div class=\"row\" style=\"margin-right: 6%;\">                        \n");
      out.write("                                    <div class=\"col-md-2 col-sm-2 \" style=\"padding-right: 0px;color: white;font-size: 25px;font-family: 'Times New Roman', serif;\">\n");
      out.write("                                        I need help with \n");
      out.write("                                    </div>                        \n");
      out.write("                                    <div class=\"col-md-4 col-sm-4\" style=\"padding-right: 0px;\">\n");
      out.write("                                        <div class=\"form-group\" style=\" position: relative; display: inline-block;width: 100%\">\n");
      out.write("                                            <select class=\"selectpicker form-control myformcontroller\" style=\"color: black;font-weight: bold;\" id=\"allprojectname\">\n");
      out.write("                                                <option>bmbmnbm</option>\n");
      out.write("                                            </select>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>                        \n");
      out.write("                                    <div class=\"col-md-2 col-sm-2 \" style=\"padding-right: 0px;color: white;font-size: 30px;font-family: 'Times New Roman', serif;\">\n");
      out.write("                                        by finding \n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-md-3 col-sm-3 \" style=\"padding-right: 0px;\">\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <select id=\"fieldname\" style=\"color: black;font-weight: bold;\" class=\"selectpicker form-control myformcontroller\">   \n");
      out.write("                                                <option>nbnmb</option>\n");
      out.write("                                            </select>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-md-1 col-sm-1 \" >\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("\n");
      out.write("                                            <div class=\"btn-holder\">\n");
      out.write("                                                <button class=\"btn btn-primary\" style=\"width:50px;padding: 4px !important; font-size:18px;\">\n");
      out.write("                                                    <i class=\"glyphicon glyphicon-search\"></i>\n");
      out.write("                                                </button>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div> \n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- //banner -->\t       \n");
      out.write("\n");
      out.write("        <!-- testimonials -->\n");
      out.write("        <div class=\"testimonials\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("\n");
      out.write("                <div class=\"w3ls_testimonials_grids\">\n");
      out.write("                    <section class=\"center slider\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </section>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- //testimonials -->\n");
      out.write("    <!-- footer -->\n");
      out.write("    <div class=\"footer\">\n");
      out.write("        <div class=\"container\">\t\t\t\t\n");
      out.write("            <div class=\"agile_footer_copy\">\n");
      out.write("                <div class=\"w3agile_footer_grids\">\n");
      out.write("                    <div class=\"col-md-4 w3agile_footer_grid\">\n");
      out.write("                        <h3>About Us</h3>\n");
      out.write("                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse.<span>Excepteur sint occaecat cupidatat \n");
      out.write("                                non proident, sunt in culpa qui officia deserunt mollit.</span></p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 w3agile_footer_grid\">\n");
      out.write("                        <h3>Contact Info</h3>\n");
      out.write("                        <ul>\n");
      out.write("                            <li><i class=\"glyphicon glyphicon-map-marker\" aria-hidden=\"true\"></i>1234k Avenue, 4th block, <span>New York City.</span></li>\n");
      out.write("                            <li><i class=\"glyphicon glyphicon-envelope\" aria-hidden=\"true\"></i><a href=\"mailto:info@example.com\">info@example.com</a></li>\n");
      out.write("                            <li><i class=\"glyphicon glyphicon-earphone\" aria-hidden=\"true\"></i>+1234 567 567</li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 w3agile_footer_grid w3agile_footer_grid1\">\n");
      out.write("                        <h3>Navigation</h3>\n");
      out.write("                        <ul>\n");
      out.write("                            <li><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span><a href=\"courses.html\">Courses</a></li>\n");
      out.write("                            <li><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span><a href=\"services.html\">Services</a></li>\t\t\t\t\t\t\t\n");
      out.write("                            <li><span class=\"glyphicon glyphicon-menu-right\" aria-hidden=\"true\"></span><a href=\"mail.html\">Mail Us</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"clearfix\"> </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"w3_agileits_copy_right_social\">\n");
      out.write("                <div class=\"col-md-6 agileits_w3layouts_copy_right\">\n");
      out.write("                    <p>&copy; 2017 Edifying. All rights reserved | Design by <a href=\"http://w3layouts.com/\">W3layouts</a></p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 w3_agile_copy_right\">\n");
      out.write("                    <ul class=\"agileinfo_social_icons\">\n");
      out.write("                        <li><a href=\"#\" class=\"w3_agileits_facebook\"><i class=\"fa fa-facebook\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"wthree_twitter\"><i class=\"fa fa-twitter\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"agileinfo_google\"><i class=\"fa fa-google-plus\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("                        <li><a href=\"#\" class=\"agileits_pinterest\"><i class=\"fa fa-pinterest-p\" aria-hidden=\"true\"></i></a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"clearfix\"> </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- //footer -->\n");
      out.write("    <!-- carousal -->\n");
      out.write("    <script src=\"buyer/assets/js/slick.js\" type=\"text/javascript\"></script>        \n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("            $(document).on('ready', function () {\n");
      out.write("                $(\".center\").slick({\n");
      out.write("                    dots: true,\n");
      out.write("                    infinite: true,\n");
      out.write("                    centerMode: true,\n");
      out.write("                    slidesToShow: 3,\n");
      out.write("                    slidesToScroll: 3,\n");
      out.write("                    responsive: [\n");
      out.write("                        {\n");
      out.write("                            breakpoint: 1366,\n");
      out.write("                            settings: {\n");
      out.write("                                arrows: true,\n");
      out.write("                                centerMode: false,\n");
      out.write("                                slidesToShow: 3\n");
      out.write("                            }\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                            breakpoint: 1024,\n");
      out.write("                            settings: {\n");
      out.write("                                arrows: true,\n");
      out.write("                                centerMode: false,\n");
      out.write("                                centerPadding: '40px',\n");
      out.write("                                slidesToShow: 2\n");
      out.write("                            }\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                            breakpoint: 480,\n");
      out.write("                            settings: {\n");
      out.write("                                arrows: true,\n");
      out.write("                                centerMode: false,\n");
      out.write("                                centerPadding: '40px',\n");
      out.write("                                slidesToShow: 1\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    ]\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("    </script>\n");
      out.write("    <!-- //carousal -->\n");
      out.write("    <!-- flexisel -->\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        $(window).load(function () {\n");
      out.write("            $(\"#flexiselDemo1\").flexisel({\n");
      out.write("                visibleItems: 4,\n");
      out.write("                animationSpeed: 1000,\n");
      out.write("                autoPlay: true,\n");
      out.write("                autoPlaySpeed: 3000,\n");
      out.write("                pauseOnHover: true,\n");
      out.write("                enableResponsiveBreakpoints: true,\n");
      out.write("                responsiveBreakpoints: {\n");
      out.write("                    portrait: {\n");
      out.write("                        changePoint: 480,\n");
      out.write("                        visibleItems: 1\n");
      out.write("                    },\n");
      out.write("                    landscape: {\n");
      out.write("                        changePoint: 640,\n");
      out.write("                        visibleItems: 2\n");
      out.write("                    },\n");
      out.write("                    tablet: {\n");
      out.write("                        changePoint: 768,\n");
      out.write("                        visibleItems: 2\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("    <script src=\"buyer/assets/js/jquery.flexisel.js\" type=\"text/javascript\"></script>        \n");
      out.write("    <!-- //flexisel -->\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- flexSlider -->\n");
      out.write("    <script src=\"buyer/assets/js/jquery.flexslider.js\" type=\"text/javascript\"></script>       \n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        $(window).load(function () {\n");
      out.write("            $('.flexslider').flexslider({\n");
      out.write("                animation: \"slide\",\n");
      out.write("                start: function (slider) {\n");
      out.write("                    $('body').removeClass('loading');\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("    <!-- //flexSlider -->\n");
      out.write("    <!-- banner-type-text -->\n");
      out.write("    <script src=\"buyer/assets/js/typed.js\" type=\"text/javascript\"></script>        \n");
      out.write("    <script>\n");
      out.write("        $(function () {\n");
      out.write("\n");
      out.write("            $(\"#typed\").typed({\n");
      out.write("                // strings: [\"Typed.js is a <strong>jQuery</strong> plugin.\", \"It <em>types</em> out sentences.\", \"And then deletes them.\", \"Try it out!\"],\n");
      out.write("                stringsElement: $('#typed-strings'),\n");
      out.write("                typeSpeed: 30,\n");
      out.write("                backDelay: 500,\n");
      out.write("                loop: false,\n");
      out.write("                contentType: 'html', // or text\n");
      out.write("                // defaults to false for infinite loop\n");
      out.write("                loopCount: false,\n");
      out.write("                callback: function () {\n");
      out.write("                    foo();\n");
      out.write("                },\n");
      out.write("                resetCallback: function () {\n");
      out.write("                    newTyped();\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $(\".reset\").click(function () {\n");
      out.write("                $(\"#typed\").typed('reset');\n");
      out.write("            });\n");
      out.write("\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        function newTyped() { /* A new typed object */\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function foo() {\n");
      out.write("            console.log(\"Callback\");\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("    <!-- //banner-type-text -->\n");
      out.write("    <!-- start-smooth-scrolling -->\n");
      out.write("    <script src=\"buyer/assets/js/move-top.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"buyer/assets/js/easing.js\" type=\"text/javascript\"></script>        \n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        jQuery(document).ready(function ($) {\n");
      out.write("            $(\".scroll\").click(function (event) {\n");
      out.write("                event.preventDefault();\n");
      out.write("                $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1000);\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("    <!-- for bootstrap working -->\n");
      out.write("    <script src=\"buyer/assets/js/bootstrap.js\" type=\"text/javascript\"></script>        \n");
      out.write("    <!-- here stars scrolling icon -->\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        $(document).ready(function () {\n");
      out.write("            $().UItoTop({easingType: 'easeOutQuart'});\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
