/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2017-01-24 14:41:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class search_005fbuyer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/servicesbuyer/jsp/header.jsp", Long.valueOf(1481731377193L));
    _jspx_dependants.put("/servicesbuyer/jsp/footer.jsp", Long.valueOf(1481731377167L));
    _jspx_dependants.put("/servicesbuyer/jsp/seached-info.jsp", Long.valueOf(1481731377235L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>               \n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <title>Cafe House Template</title>\n");
      out.write("\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' rel='stylesheet' type='text/css'>\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Damion' rel='stylesheet' type='text/css'>\n");
      out.write("        \n");
      out.write("        <link href=\"servicesbuyer/assets/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"servicesbuyer/assets/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        \n");
      out.write("        <link href=\"servicesbuyer/assets/css/custom.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        \n");
      out.write("        <link href=\"servicesbuyer/assets/css/search-bar.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"servicesbuyer/assets/css/templatemo-style.css\" rel=\"stylesheet\" type=\"text/css\"/>        \n");
      out.write("\n");
      out.write("        <link rel=\"shortcut icon\" href=\"servicesbuyer/assets/img/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("                \n");
      out.write("        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("        <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("        <![endif]-->\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!-- Preloader -->\n");
      out.write("        <div id=\"loader-wrapper\">\n");
      out.write("            <div id=\"loader\"></div>\n");
      out.write("            <div class=\"loader-section section-left\"></div>\n");
      out.write("            <div class=\"loader-section section-right\"></div>\n");
      out.write("        </div>\n");
      out.write("        <!-- End Preloader -->\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"tm-top-header\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"tm-top-header-inner\">\n");
      out.write("                <div class=\"tm-logo-container\">\n");
      out.write("                    <img src=\"servicesbuyer/assets/images/logo5.png\" style=\"width:150px;padding: 0px;margin: 0px;\" alt=\"Logo\" class=\"tm-site-logo\"> <!--error image-->                    \n");
      out.write("                    <!--<h1 class=\"tm-site-name\" style=\"color: yellow\">MyHero </h1>-->\n");
      out.write("                    <!--<h5 style=\"margin: 0px;padding: 0px;\">connecting the unconnected</h5>-->\n");
      out.write("                   \n");
      out.write("                </div>\n");
      out.write("                <div class=\"mobile-menu-icon\">\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\n");
      out.write("                </div>\n");
      out.write("                <nav class=\"tm-nav\">\n");
      out.write("                    <ul>                        \n");
      out.write("                        <li ><a href=\"index.html\">ප්‍රනීත් මදුසංක</a></li>\n");
      out.write("                        <li ><a href=\"index.html\" style=\"color: yellow\">ABOUT US</a></li>                        \n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"javascript:void(0);\" onclick=\"loadSignIn();\" style=\"color: yellow;\">Sign In</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li style=\"padding: 15px;\">\n");
      out.write("                            <select style=\"color: black;margin-left: 20px;\">\n");
      out.write("                                <option value=\"volvo\">English</option>\n");
      out.write("                                <option value=\"volvo\">සිංහල</option>\n");
      out.write("                            </select>                            \n");
      out.write("                        </li>                                                \n");
      out.write("                    </ul>\n");
      out.write("                </nav>                 \n");
      out.write("            </div>           \n");
      out.write("        </div>    \n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("           <!--header file-->    \n");
      out.write("\n");
      out.write("        <div class=\"tm-main-section light-gray-bg\">\n");
      out.write("            <div class=\"container\" id=\"main\" >  \n");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<section class=\"tm-section row\">\n");
      out.write("\n");
      out.write("    <div class=\"col-lg-12 tm-section-header-container margin-bottom-30\">\n");
      out.write("        <h2 class=\"tm-section-header gold-text\" style=\"color: yellow;text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;\"><img src=\"servicesbuyer/assets/img/logo.pngs\" class=\"tm-site-logo\"> House work</h2>\n");
      out.write("        <div class=\"tm-hr-container\"><hr class=\"tm-hr\"></div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div>\n");
      out.write("\n");
      out.write("        <div class=\"col-lg-3 col-md-3 hidden-div\" style=\"background-color: window\">\n");
      out.write("            <div class=\"tm-position-relative margin-bottom-30\">              \n");
      out.write("                <nav class=\"tm-side-menu\">\n");
      out.write("                    <ul style=\"text-align: center\">\n");
      out.write("                        <li><a href=\"#\" class=\"active\"><u>Search Option</u></a></li>\n");
      out.write("                    </ul>\n");
      out.write("                    <ul style=\"text-align: left\">\n");
      out.write("                        <li><a href=\"#\"><input type=\"radio\" name=\"one\" value=\"one\" checked> Most Recent<br></a></li>\n");
      out.write("                        <li><a href=\"#\"><input type=\"radio\" name=\"one\" value=\"one\"> Popular Search<br></a></li>\n");
      out.write("                        <hr>\n");
      out.write("                        <li><a href=\"#\"><input type=\"radio\" name=\"two\" value=\"two\" checked> Best Ranking<br></a></li>\n");
      out.write("                        <li><a href=\"#\"><input type=\"radio\" name=\"two\" value=\"two\"> Best Rating<br></a></li>\n");
      out.write("                        <hr>\n");
      out.write("\n");
      out.write("                        <div id=\"sidebar-menu\" class=\"main_menu_side hidden-print main_menu\">\n");
      out.write("                            <div class=\"menu_section\">\n");
      out.write("                                <ul class=\"nav side-menu\">\n");
      out.write("                                    <li><a><i class=\"fa fa-list-ul\"></i> Select Category <span class=\"fa fa-chevron-down\"></span></a>\n");
      out.write("                                        <ul class=\"nav child_menu\">\n");
      out.write("                                            <li><a href=\"index.html\"><input type=\"radio\" name=\"two\" value=\"two\"> Dashboard</a></li>\n");
      out.write("                                            <li><a href=\"index2.html\"><input type=\"radio\" name=\"two\" value=\"two\"> Dashboard2</a></li>\n");
      out.write("                                            <li><a href=\"index3.html\"><input type=\"radio\" name=\"two\" value=\"two\"> Dashboard3</a></li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </li>\n");
      out.write("                                    <hr>\n");
      out.write("                                    <li><a><i class=\"fa fa-list-ul\"></i> Select Age <span class=\"fa fa-chevron-down\"></span></a>\n");
      out.write("                                        <ul class=\"nav child_menu\">\n");
      out.write("                                            <li><a href=\"form.html\">General Form</a></li>\n");
      out.write("                                            <li><a href=\"form_advanced.html\">Advanced Components</a></li>\n");
      out.write("                                            <li><a href=\"form_validation.html\">Form Validation</a></li>\n");
      out.write("                                            <li><a href=\"form_wizards.html\">Form Wizard</a></li>\n");
      out.write("                                            <li><a href=\"form_upload.html\">Form Upload</a></li>\n");
      out.write("                                            <li><a href=\"form_buttons.html\">Form Buttons</a></li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </li>\n");
      out.write("                                    <hr>\n");
      out.write("                                    <li><a><i class=\"fa fa-list-ul\"></i> Select Prise <span class=\"fa fa-chevron-down\"></span></a>\n");
      out.write("                                        <ul class=\"nav child_menu\">\n");
      out.write("                                            <li><a href=\"general_elements.html\">General Elements</a></li>\n");
      out.write("                                            <li><a href=\"media_gallery.html\">Media Gallery</a></li>\n");
      out.write("                                            <li><a href=\"typography.html\">Typography</a></li>\n");
      out.write("                                            <li><a href=\"icons.html\">Icons</a></li>\n");
      out.write("                                            <li><a href=\"glyphicons.html\">Glyphicons</a></li>\n");
      out.write("                                            <li><a href=\"widgets.html\">Widgets</a></li>\n");
      out.write("                                            <li><a href=\"invoice.html\">Invoice</a></li>\n");
      out.write("                                            <li><a href=\"inbox.html\">Inbox</a></li>\n");
      out.write("                                            <li><a href=\"calendar.html\">Calendar</a></li>\n");
      out.write("                                        </ul>\n");
      out.write("                                    </li>                                                                                                            \n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                        </div>                                             \n");
      out.write("                    </ul>              \n");
      out.write("                </nav>    \n");
      out.write("                <!--<img src=\"servicesbuyer/assets/img/vertical-menu-bg.png\" alt=\"Menu bg\" class=\"tm-side-menu-bg\">-->\n");
      out.write("            </div>  \n");
      out.write("        </div>  \n");
      out.write("\n");
      out.write("        <!--All search details div tag-->\n");
      out.write("        <div class=\"tm-menu-product-content col-lg-7 col-md-7\" style=\"padding-left: 12px;padding-right: 1px;\"> <!-- menu content -->\n");
      out.write("\n");
      out.write("            <!--first one div tage-->\n");
      out.write("            <div class=\"tm-product\">                \n");
      out.write("                <div class=\"col-xs-4\">                   \n");
      out.write("                    <img src=\"servicesbuyer/assets/img/menu-1.jpg\" alt=\"Product\" style=\"height: 200px;width: 136px;\">                                                               \n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xs-8\" style=\"margin: 0px;padding: 0px;\">                    \n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <div class=\"col-xs-8\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                            <div class=\"tm-product-text\">\n");
      out.write("                                <h3 class=\"tm-product-title\" style=\"margin-bottom: 0px;padding-bottom: 0px;text-align: center\"><u>Housework – Is It A Boon Or Bane?</u></h3>                        \n");
      out.write("                            </div> \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xs-4\" style=\"margin: 0px;padding: 0px;display:table-cell; vertical-align:middle; text-align:center\">\n");
      out.write("                            <img src=\"http://devilsworkshop.org/files/2013/01/small-facebook-profile-picture.jpg\" style=\"width: 50px;height: 50px;border-radius: 150px;\" alt=\"Product\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <div class=\"col-xs-8\">\n");
      out.write("                            <ul><br>\n");
      out.write("                                <li>077 - 425 8006</li>\n");
      out.write("                                <li>24 year.</li>\n");
      out.write("                                <li>Location: <a href=\"\">Aluthgama</a></li>                                \n");
      out.write("                                <li>wpraneethmadusanka@gmail.com</li>\n");
      out.write("                                <li style=\"font-size: 13px;\">company rating: <progress max=\"100\" value=\"80\" style=\"width: 100px;\"></progress></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xs-4\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                            <p style=\"font-size: 10px;margin: 0px;padding: 0px;text-align: center;\"><u>praneeth madusanka</u></p>\n");
      out.write("                            <p style=\"font-size: 10px;text-align: center;margin: 0px;padding: 0px\">customer rating:</p>\n");
      out.write("                            <p style=\"font-size: 24px;margin: 0px;padding: 0px;text-align: center;background-color: skyblue\">\n");
      out.write("                            <fieldset class=\"rating\">\n");
      out.write("                                <input type=\"radio\" id=\"star5\" name=\"rating\" value=\"5\" /><label class = \"full\" for=\"star5\" title=\"Awesome - 5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4half\" name=\"rating\" value=\"4 and a half\" /><label class=\"half\" for=\"star4half\" title=\"Pretty good - 4.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4\" name=\"rating\" value=\"4\" /><label class = \"full\" for=\"star4\" title=\"Pretty good - 4 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3half\" name=\"rating\" value=\"3 and a half\" /><label class=\"half\" for=\"star3half\" title=\"Meh - 3.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3\" name=\"rating\" value=\"3\" /><label class = \"full\" for=\"star3\" title=\"Meh - 3 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2half\" name=\"rating\" value=\"2 and a half\" /><label class=\"half\" for=\"star2half\" title=\"Kinda bad - 2.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2\" name=\"rating\" value=\"2\" /><label class = \"full\" for=\"star2\" title=\"Kinda bad - 2 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1half\" name=\"rating\" value=\"1 and a half\" /><label class=\"half\" for=\"star1half\" title=\"Meh - 1.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1\" name=\"rating\" value=\"1\" /><label class = \"full\" for=\"star1\" title=\"Sucks big time - 1 star\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"starhalf\" name=\"rating\" value=\"half\" /><label class=\"half\" for=\"starhalf\" title=\"Sucks big time - 0.5 stars\"></label>\n");
      out.write("                            </fieldset>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <p style=\"font-size: 12px;margin: 0px;padding: 0px;text-align: left;width: 300px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;color: blue\">\n");
      out.write("                            Bane leaflets use choresa and house list chores buying essay appreciative covenants. Buying say essay house buying if list had house essay or a boon chores\n");
      out.write("                        </p><input style=\"font-size: 10px;color: blue;float: right\" type=\"button\" value=\"more info\"/>\n");
      out.write("                    </div>\n");
      out.write("                </div>                                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--first one div tage-->\n");
      out.write("            <div class=\"tm-product\">                \n");
      out.write("                <div class=\"col-xs-4\">                   \n");
      out.write("                    <img src=\"servicesbuyer/assets/img/menu-1.jpg\" alt=\"Product\" style=\"height: 200px;width: 136px;\">                                                               \n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xs-8\" style=\"margin: 0px;padding: 0px;\">                    \n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <div class=\"col-xs-8\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                            <div class=\"tm-product-text\">\n");
      out.write("                                <h3 class=\"tm-product-title\" style=\"margin-bottom: 0px;padding-bottom: 0px;text-align: center\"><u>Housework – Is It A Boon Or Bane?</u></h3>                        \n");
      out.write("                            </div> \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xs-4\" style=\"margin: 0px;padding: 0px;display:table-cell; vertical-align:middle; text-align:center\">\n");
      out.write("                            <img src=\"http://devilsworkshop.org/files/2013/01/small-facebook-profile-picture.jpg\" style=\"width: 50px;height: 50px;border-radius: 150px;\" alt=\"Product\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <div class=\"col-xs-8\">\n");
      out.write("                            <ul><br>\n");
      out.write("                                <li>077 - 425 8006</li>\n");
      out.write("                                <li>24 year.</li>\n");
      out.write("                                <li>Location: <a href=\"\">Aluthgama</a></li>                                \n");
      out.write("                                <li>wpraneethmadusanka@gmail.com</li>\n");
      out.write("                                <li style=\"font-size: 13px;\">company rating: <progress max=\"100\" value=\"80\" style=\"width: 100px;\"></progress></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xs-4\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                            <p style=\"font-size: 10px;margin: 0px;padding: 0px;text-align: center;\"><u>praneeth madusanka</u></p>\n");
      out.write("                            <p style=\"font-size: 10px;text-align: center;margin: 0px;padding: 0px\">customer rating:</p>\n");
      out.write("                            <p style=\"font-size: 24px;margin: 0px;padding: 0px;text-align: center;background-color: skyblue\">\n");
      out.write("                            <fieldset class=\"rating\">\n");
      out.write("                                <input type=\"radio\" id=\"star5\" name=\"rating\" value=\"5\" /><label class = \"full\" for=\"star5\" title=\"Awesome - 5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4half\" name=\"rating\" value=\"4 and a half\" /><label class=\"half\" for=\"star4half\" title=\"Pretty good - 4.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4\" name=\"rating\" value=\"4\" /><label class = \"full\" for=\"star4\" title=\"Pretty good - 4 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3half\" name=\"rating\" value=\"3 and a half\" /><label class=\"half\" for=\"star3half\" title=\"Meh - 3.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3\" name=\"rating\" value=\"3\" /><label class = \"full\" for=\"star3\" title=\"Meh - 3 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2half\" name=\"rating\" value=\"2 and a half\" /><label class=\"half\" for=\"star2half\" title=\"Kinda bad - 2.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2\" name=\"rating\" value=\"2\" /><label class = \"full\" for=\"star2\" title=\"Kinda bad - 2 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1half\" name=\"rating\" value=\"1 and a half\" /><label class=\"half\" for=\"star1half\" title=\"Meh - 1.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1\" name=\"rating\" value=\"1\" /><label class = \"full\" for=\"star1\" title=\"Sucks big time - 1 star\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"starhalf\" name=\"rating\" value=\"half\" /><label class=\"half\" for=\"starhalf\" title=\"Sucks big time - 0.5 stars\"></label>\n");
      out.write("                            </fieldset>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <p style=\"font-size: 12px;margin: 0px;padding: 0px;text-align: left;width: 300px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;color: blue\">\n");
      out.write("                            Bane leaflets use choresa and house list chores buying essay appreciative covenants. Buying say essay house buying if list had house essay or a boon chores\n");
      out.write("                        </p><input style=\"font-size: 10px;color: blue;float: right\" type=\"button\" value=\"more info\"/>\n");
      out.write("                    </div>\n");
      out.write("                </div>                                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--first one div tage-->\n");
      out.write("            <div class=\"tm-product\">                \n");
      out.write("                <div class=\"col-xs-4\">                   \n");
      out.write("                    <img src=\"servicesbuyer/assets/img/menu-1.jpg\" alt=\"Product\" style=\"height: 200px;width: 136px;\">                                                               \n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xs-8\" style=\"margin: 0px;padding: 0px;\">                    \n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <div class=\"col-xs-8\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                            <div class=\"tm-product-text\">\n");
      out.write("                                <h3 class=\"tm-product-title\" style=\"margin-bottom: 0px;padding-bottom: 0px;text-align: center\"><u>Housework – Is It A Boon Or Bane?</u></h3>                        \n");
      out.write("                            </div> \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xs-4\" style=\"margin: 0px;padding: 0px;display:table-cell; vertical-align:middle; text-align:center\">\n");
      out.write("                            <img src=\"http://devilsworkshop.org/files/2013/01/small-facebook-profile-picture.jpg\" style=\"width: 50px;height: 50px;border-radius: 150px;\" alt=\"Product\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <div class=\"col-xs-8\">\n");
      out.write("                            <ul><br>\n");
      out.write("                                <li>077 - 425 8006</li>\n");
      out.write("                                <li>24 year.</li>\n");
      out.write("                                <li>Location: <a href=\"\">Aluthgama</a></li>                                \n");
      out.write("                                <li>wpraneethmadusanka@gmail.com</li>\n");
      out.write("                                <li style=\"font-size: 13px;\">company rating: <progress max=\"100\" value=\"80\" style=\"width: 100px;\"></progress></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xs-4\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                            <p style=\"font-size: 10px;margin: 0px;padding: 0px;text-align: center;\"><u>praneeth madusanka</u></p>\n");
      out.write("                            <p style=\"font-size: 10px;text-align: center;margin: 0px;padding: 0px\">customer rating:</p>\n");
      out.write("                            <p style=\"font-size: 24px;margin: 0px;padding: 0px;text-align: center;background-color: skyblue\">\n");
      out.write("                            <fieldset class=\"rating\">\n");
      out.write("                                <input type=\"radio\" id=\"star5\" name=\"rating\" value=\"5\" /><label class = \"full\" for=\"star5\" title=\"Awesome - 5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4half\" name=\"rating\" value=\"4 and a half\" /><label class=\"half\" for=\"star4half\" title=\"Pretty good - 4.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4\" name=\"rating\" value=\"4\" /><label class = \"full\" for=\"star4\" title=\"Pretty good - 4 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3half\" name=\"rating\" value=\"3 and a half\" /><label class=\"half\" for=\"star3half\" title=\"Meh - 3.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3\" name=\"rating\" value=\"3\" /><label class = \"full\" for=\"star3\" title=\"Meh - 3 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2half\" name=\"rating\" value=\"2 and a half\" /><label class=\"half\" for=\"star2half\" title=\"Kinda bad - 2.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2\" name=\"rating\" value=\"2\" /><label class = \"full\" for=\"star2\" title=\"Kinda bad - 2 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1half\" name=\"rating\" value=\"1 and a half\" /><label class=\"half\" for=\"star1half\" title=\"Meh - 1.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1\" name=\"rating\" value=\"1\" /><label class = \"full\" for=\"star1\" title=\"Sucks big time - 1 star\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"starhalf\" name=\"rating\" value=\"half\" /><label class=\"half\" for=\"starhalf\" title=\"Sucks big time - 0.5 stars\"></label>\n");
      out.write("                            </fieldset>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <p style=\"font-size: 12px;margin: 0px;padding: 0px;text-align: left;width: 300px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;color: blue\">\n");
      out.write("                            Bane leaflets use choresa and house list chores buying essay appreciative covenants. Buying say essay house buying if list had house essay or a boon chores\n");
      out.write("                        </p><input style=\"font-size: 10px;color: blue;float: right\" type=\"button\" value=\"more info\"/>\n");
      out.write("                    </div>\n");
      out.write("                </div>                                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--first one div tage-->\n");
      out.write("            <div class=\"tm-product\">                \n");
      out.write("                <div class=\"col-xs-4\">                   \n");
      out.write("                    <img src=\"servicesbuyer/assets/img/menu-1.jpg\" alt=\"Product\" style=\"height: 200px;width: 136px;\">                                                               \n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xs-8\" style=\"margin: 0px;padding: 0px;\">                    \n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <div class=\"col-xs-8\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                            <div class=\"tm-product-text\">\n");
      out.write("                                <h3 class=\"tm-product-title\" style=\"margin-bottom: 0px;padding-bottom: 0px;text-align: center\"><u>Housework – Is It A Boon Or Bane?</u></h3>                        \n");
      out.write("                            </div> \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xs-4\" style=\"margin: 0px;padding: 0px;display:table-cell; vertical-align:middle; text-align:center\">\n");
      out.write("                            <img src=\"http://devilsworkshop.org/files/2013/01/small-facebook-profile-picture.jpg\" style=\"width: 50px;height: 50px;border-radius: 150px;\" alt=\"Product\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <div class=\"col-xs-8\">\n");
      out.write("                            <ul><br>\n");
      out.write("                                <li>077 - 425 8006</li>\n");
      out.write("                                <li>24 year.</li>\n");
      out.write("                                <li>Location: <a href=\"\">Aluthgama</a></li>                                \n");
      out.write("                                <li>wpraneethmadusanka@gmail.com</li>\n");
      out.write("                                <li style=\"font-size: 13px;\">company rating: <progress max=\"100\" value=\"80\" style=\"width: 100px;\"></progress></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xs-4\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                            <p style=\"font-size: 10px;margin: 0px;padding: 0px;text-align: center;\"><u>praneeth madusanka</u></p>\n");
      out.write("                            <p style=\"font-size: 10px;text-align: center;margin: 0px;padding: 0px\">customer rating:</p>\n");
      out.write("                            <p style=\"font-size: 24px;margin: 0px;padding: 0px;text-align: center;background-color: skyblue\">\n");
      out.write("                            <fieldset class=\"rating\">\n");
      out.write("                                <input type=\"radio\" id=\"star5\" name=\"rating\" value=\"5\" /><label class = \"full\" for=\"star5\" title=\"Awesome - 5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4half\" name=\"rating\" value=\"4 and a half\" /><label class=\"half\" for=\"star4half\" title=\"Pretty good - 4.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4\" name=\"rating\" value=\"4\" /><label class = \"full\" for=\"star4\" title=\"Pretty good - 4 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3half\" name=\"rating\" value=\"3 and a half\" /><label class=\"half\" for=\"star3half\" title=\"Meh - 3.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3\" name=\"rating\" value=\"3\" /><label class = \"full\" for=\"star3\" title=\"Meh - 3 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2half\" name=\"rating\" value=\"2 and a half\" /><label class=\"half\" for=\"star2half\" title=\"Kinda bad - 2.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2\" name=\"rating\" value=\"2\" /><label class = \"full\" for=\"star2\" title=\"Kinda bad - 2 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1half\" name=\"rating\" value=\"1 and a half\" /><label class=\"half\" for=\"star1half\" title=\"Meh - 1.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1\" name=\"rating\" value=\"1\" /><label class = \"full\" for=\"star1\" title=\"Sucks big time - 1 star\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"starhalf\" name=\"rating\" value=\"half\" /><label class=\"half\" for=\"starhalf\" title=\"Sucks big time - 0.5 stars\"></label>\n");
      out.write("                            </fieldset>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <p style=\"font-size: 12px;margin: 0px;padding: 0px;text-align: left;width: 300px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;color: blue\">\n");
      out.write("                            Bane leaflets use choresa and house list chores buying essay appreciative covenants. Buying say essay house buying if list had house essay or a boon chores\n");
      out.write("                        </p><input style=\"font-size: 10px;color: blue;float: right\" type=\"button\" value=\"more info\"/>\n");
      out.write("                    </div>\n");
      out.write("                </div>                                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!--first one div tage-->\n");
      out.write("            <div class=\"tm-product\">                \n");
      out.write("                <div class=\"col-xs-4\">                   \n");
      out.write("                    <img src=\"servicesbuyer/assets/img/menu-1.jpg\" alt=\"Product\" style=\"height: 200px;width: 136px;\">                                                               \n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-xs-8\" style=\"margin: 0px;padding: 0px;\">                    \n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <div class=\"col-xs-8\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                            <div class=\"tm-product-text\">\n");
      out.write("                                <h3 class=\"tm-product-title\" style=\"margin-bottom: 0px;padding-bottom: 0px;text-align: center\"><u>Housework – Is It A Boon Or Bane?</u></h3>                        \n");
      out.write("                            </div> \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xs-4\" style=\"margin: 0px;padding: 0px;display:table-cell; vertical-align:middle; text-align:center\">\n");
      out.write("                            <img src=\"http://devilsworkshop.org/files/2013/01/small-facebook-profile-picture.jpg\" style=\"width: 50px;height: 50px;border-radius: 150px;\" alt=\"Product\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <div class=\"col-xs-8\">\n");
      out.write("                            <ul><br>\n");
      out.write("                                <li>077 - 425 8006</li>\n");
      out.write("                                <li>24 year.</li>\n");
      out.write("                                <li>Location: <a href=\"\">Aluthgama</a></li>                                \n");
      out.write("                                <li>wpraneethmadusanka@gmail.com</li>\n");
      out.write("                                <li style=\"font-size: 13px;\">company rating: <progress max=\"100\" value=\"80\" style=\"width: 100px;\"></progress></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xs-4\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                            <p style=\"font-size: 10px;margin: 0px;padding: 0px;text-align: center;\"><u>praneeth madusanka</u></p>\n");
      out.write("                            <p style=\"font-size: 10px;text-align: center;margin: 0px;padding: 0px\">customer rating:</p>\n");
      out.write("                            <p style=\"font-size: 24px;margin: 0px;padding: 0px;text-align: center;background-color: skyblue\">\n");
      out.write("                            <fieldset class=\"rating\">\n");
      out.write("                                <input type=\"radio\" id=\"star5\" name=\"rating\" value=\"5\" /><label class = \"full\" for=\"star5\" title=\"Awesome - 5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4half\" name=\"rating\" value=\"4 and a half\" /><label class=\"half\" for=\"star4half\" title=\"Pretty good - 4.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star4\" name=\"rating\" value=\"4\" /><label class = \"full\" for=\"star4\" title=\"Pretty good - 4 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3half\" name=\"rating\" value=\"3 and a half\" /><label class=\"half\" for=\"star3half\" title=\"Meh - 3.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star3\" name=\"rating\" value=\"3\" /><label class = \"full\" for=\"star3\" title=\"Meh - 3 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2half\" name=\"rating\" value=\"2 and a half\" /><label class=\"half\" for=\"star2half\" title=\"Kinda bad - 2.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star2\" name=\"rating\" value=\"2\" /><label class = \"full\" for=\"star2\" title=\"Kinda bad - 2 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1half\" name=\"rating\" value=\"1 and a half\" /><label class=\"half\" for=\"star1half\" title=\"Meh - 1.5 stars\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"star1\" name=\"rating\" value=\"1\" /><label class = \"full\" for=\"star1\" title=\"Sucks big time - 1 star\"></label>\n");
      out.write("                                <input type=\"radio\" id=\"starhalf\" name=\"rating\" value=\"half\" /><label class=\"half\" for=\"starhalf\" title=\"Sucks big time - 0.5 stars\"></label>\n");
      out.write("                            </fieldset>\n");
      out.write("                            </p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-12\" style=\"margin: 0px;padding: 0px;\">\n");
      out.write("                        <p style=\"font-size: 12px;margin: 0px;padding: 0px;text-align: left;width: 300px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;color: blue\">\n");
      out.write("                            Bane leaflets use choresa and house list chores buying essay appreciative covenants. Buying say essay house buying if list had house essay or a boon chores\n");
      out.write("                        </p><input style=\"font-size: 10px;color: blue;float: right\" type=\"button\" value=\"more info\"/>\n");
      out.write("                    </div>\n");
      out.write("                </div>                                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!--advertisement div tag-->\n");
      out.write("        <div class=\"col-lg-2 col-md-2\" style=\"padding-left: 15px;padding-right: 15px;\">\n");
      out.write("            <div class=\"tm-position-relative margin-bottom-30\" style=\"background-color: #000;height: 400px;\">                                                                                \n");
      out.write("                <!--<img src=\"\" alt=\"Menu bg\" class=\"tm-side-menu-bg\">-->\n");
      out.write("            </div>  \n");
      out.write("        </div>\n");
      out.write("    </div>  \n");
      out.write("\n");
      out.write("    <div class=\"col-lg-12 col-md-12 tm-section-header-container margin-bottom-30\">\n");
      out.write("        <div class=\"tm-hr-container\"><hr class=\"tm-hr\"></div>\n");
      out.write("        <h2 class=\"tm-section-header\" style=\"color: blue;font-size: 16px;\"><a href=\"\"> Next page>></a></h2>        \n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div> \n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"tm-black-bg\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row margin-bottom-60\">\n");
      out.write("                <nav class=\"col-lg-3 col-md-3 tm-footer-nav tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>Main Menu</u></h3>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">Home</a></li>\n");
      out.write("                        <li><a href=\"#\">About Us</a></li>\n");
      out.write("                        <li><a href=\"#\">Privacy Policy</a></li>                        \n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <div class=\"col-lg-5 col-md-5 tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>About Us</u></h3>\n");
      out.write("                    <!--<p class=\"margin-top-15\">Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet.</p>-->\n");
      out.write("                    <p class=\"margin-top-15\">\n");
      out.write("                        OnGoing Solution (Pvt) Ltd.<br>\n");
      out.write("                        No xx, Xxxxxx,<br>\n");
      out.write("                        Colombo 0x,<br>\n");
      out.write("                        Sri Lanka.<br><br>\n");
      out.write("                        E-mail: emailaddress@gail.com<br>\n");
      out.write("                        Tel No: 091 41 05 172\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>Get Social</u></h3>\n");
      out.write("                    <!--<p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante.</p>-->\n");
      out.write("                    <div class=\"tm-social-icons-container\">\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-linkedin\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-youtube\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-behance\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                    <br>\n");
      out.write("                    <p style=\"font-size: 16px;\"><i class=\"fa fa-android\" aria-hidden=\"true\"></i> <a href=\"\"> Download app for Android.</a></p>\n");
      out.write("                    <p style=\"font-size: 16px;\"><i class=\"fa fa-apple\" aria-hidden=\"true\"></i> <a href=\"\"> Download app for iOS.</a></p>                    \n");
      out.write("                </div>\n");
      out.write("            </div>          \n");
      out.write("        </div>  \n");
      out.write("    </div>      \n");
      out.write("    <div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row tm-copyright\">\n");
      out.write("                <p class=\"col-lg-12 small copyright-text text-center\">Copyright &copy; 2016 OnGoing Solution</p>\n");
      out.write("            </div>  \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer> ");
      out.write("           <!-- Footer content-->\n");
      out.write("\n");
      out.write("        <!-- JS -->\n");
      out.write("        <script src=\"servicesbuyer/assets/js/jquery-1.11.2.min.js\" type=\"text/javascript\"></script>         <!-- jQuery -->        \n");
      out.write("        <script src=\"servicesbuyer/assets/js/templatemo-script.js\" type=\"text/javascript\"></script>         <!-- Templatemo Script -->\n");
      out.write("        \n");
      out.write("        <script src=\"servicesbuyer/assets/js/custom.js\" type=\"text/javascript\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
