/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2017-03-15 19:33:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\t\n");
      out.write("        <meta http-equiv=\"Cache-control\" content=\"no-cache\">\n");
      out.write("        <link rel=\"shortcut icon\" href=\"login/css/images/mobitel.ico\">\n");
      out.write("        <title>Login Page</title>\n");
      out.write("        <!-- bootstrap & fontawesome -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"login/css/bootstrap.min.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"login/css/font-awesome.min.css\" />\n");
      out.write("\n");
      out.write("        <!-- text fonts -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"login/css/fonts.css\" />\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"login/css/ace.min.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"login/css/ace-rtl.min.css\" />\n");
      out.write("        <script src=\"login/js/jquery.min.js\"></script>\n");
      out.write("        <script src=\"http://jquerypp.com/release/latest/jquerypp.js\"></script> \n");
      out.write("        <script src=\"login/implementation/bootstrap-notify.js\"></script> \n");
      out.write("        <style>\n");
      out.write("            [data-notify=\"container\"]{\n");
      out.write("                background-color: #bce8f1;\n");
      out.write("            }\n");
      out.write("            [data-notify=\"container\"].alert-pastel-mywarning {\n");
      out.write("                background-color: #ff3333;\n");
      out.write("            }\n");
      out.write("            [data-notify=\"container\"].alert-pastel-myinfo {\n");
      out.write("                background-color: #ffff4d;\n");
      out.write("            }        \n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body class=\"login-layout\">\n");
      out.write("        <div class=\"main-container\">\n");
      out.write("            <div class=\"main-content\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-sm-10 col-sm-offset-1\">\n");
      out.write("                        <div class=\"login-container\">\n");
      out.write("                            <div class=\"center\">\n");
      out.write("                                <h1>\n");
      out.write("                                    <i class=\"\"><img src=\"login/img/Special Mobitel sms package with 1500 free minutes.png\" style=\"width: 80px\"/></i>\n");
      out.write("                                    <span class=\"red\">:</span>\n");
      out.write("                                    <span class=\"white\" id=\"id-text2\">Application</span>\n");
      out.write("                                </h1>\n");
      out.write("                                <h4 class=\"blue\" id=\"id-company-text\">&copy; Mobitel Engineering(Pvt) Ltd.</h4>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"space-6\"></div>\n");
      out.write("\n");
      out.write("                            <div class=\"position-relative\">\n");
      out.write("                                <div id=\"login-box\" class=\"login-box visible widget-box no-border\">\n");
      out.write("                                    <div class=\"widget-body\">\n");
      out.write("                                        <div class=\"widget-main center\">\n");
      out.write("                                            <h5 id=\"invalidusername\" style=\"color: red\"></h5>\n");
      out.write("                                            <h4 class=\"header blue lighter bigger\">\n");
      out.write("                                                <i class=\"ace-icon fa fa-coffee green\"></i>\n");
      out.write("                                                Please Enter Your Information\n");
      out.write("                                            </h4>\n");
      out.write("\n");
      out.write("                                            <div class=\"space-6\"></div>\n");
      out.write("\n");
      out.write("                                            <form>\n");
      out.write("                                                <fieldset>\n");
      out.write("                                                    <label class=\"block clearfix\">\n");
      out.write("                                                        <span class=\"block input-icon input-icon-right\">\n");
      out.write("                                                            <input type=\"text\" class=\"form-control\" id=\"userName\" placeholder=\"Username\" />\n");
      out.write("                                                            <i class=\"ace-icon fa fa-user\"></i>\n");
      out.write("                                                        </span>\n");
      out.write("                                                    </label>\n");
      out.write("\n");
      out.write("                                                    <label class=\"block clearfix\">\n");
      out.write("                                                        <span class=\"block input-icon input-icon-right\">\n");
      out.write("                                                            <input type=\"password\" class=\"form-control\" id=\"passWord\" placeholder=\"Password\" />\n");
      out.write("                                                            <i class=\"ace-icon fa fa-lock\"></i>\n");
      out.write("                                                        </span>\n");
      out.write("                                                    </label>\n");
      out.write("\n");
      out.write("                                                    <div class=\"space\"></div>\n");
      out.write("\n");
      out.write("                                                    <div class=\"clearfix\">\n");
      out.write("                                                        <label class=\"inline\">\n");
      out.write("                                                            <input id=\"rememberme\" type=\"checkbox\" class=\"ace\" />\n");
      out.write("                                                            <span class=\"lbl\"> Remember Me</span>\n");
      out.write("                                                        </label>\n");
      out.write("\n");
      out.write("                                                        <button type=\"button\" id=\"\" class=\"width-35 pull-right btn btn-sm btn-primary\" onclick=\"loadLoginValidation();\">                                                            \n");
      out.write("                                                            <i class=\"ace-icon fa fa-key\"></i>\n");
      out.write("                                                            <span class=\"bigger-110\">Login</span>\n");
      out.write("                                                        </button>\n");
      out.write("                                                    </div>\n");
      out.write("\n");
      out.write("                                                    <div class=\"space-4\"></div>\n");
      out.write("                                                </fieldset>\n");
      out.write("                                            </form>\n");
      out.write("\n");
      out.write("                                            <div class=\"social-or-login center\">\n");
      out.write("                                                <span class=\"bigger-110\">Or Login Using</span>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div class=\"space-6\"></div>\n");
      out.write("\n");
      out.write("                                            <div class=\"social-login center\">\n");
      out.write("                                                <a class=\"btn btn-primary\">\n");
      out.write("                                                    <i class=\"ace-icon fa fa-facebook\"></i>\n");
      out.write("                                                </a>\n");
      out.write("\n");
      out.write("                                                <a class=\"btn btn-info\">\n");
      out.write("                                                    <i class=\"ace-icon fa fa-twitter\"></i>\n");
      out.write("                                                </a>\n");
      out.write("\n");
      out.write("                                                <a class=\"btn btn-danger\">\n");
      out.write("                                                    <i class=\"ace-icon fa fa-google-plus\"></i>\n");
      out.write("                                                </a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div><!-- /.widget-main -->\n");
      out.write("\n");
      out.write("                                        <div class=\"toolbar clearfix\">\n");
      out.write("                                            <div>\n");
      out.write("                                                <a href=\"#\" data-target=\"#forgot-box\" class=\"forgot-password-link\">\n");
      out.write("                                                    <i class=\"ace-icon fa fa-arrow-left\"></i>\n");
      out.write("                                                    I forgot my password\n");
      out.write("                                                </a>\n");
      out.write("                                            </div>\n");
      out.write("\n");
      out.write("                                            <div>\n");
      out.write("                                                <a href=\"#\" data-target=\"#signup-box\" class=\"user-signup-link\">\n");
      out.write("                                                    I want to register\n");
      out.write("                                                    <i class=\"ace-icon fa fa-arrow-right\"></i>\n");
      out.write("                                                </a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div><!-- /.widget-body -->\n");
      out.write("                                </div><!-- /.login-box -->\n");
      out.write("\n");
      out.write("                                <div id=\"forgot-box\" class=\"forgot-box widget-box no-border\">\n");
      out.write("                                    <div class=\"widget-body\">\n");
      out.write("                                        <div class=\"widget-main\">\n");
      out.write("                                            <h4 class=\"header red lighter bigger\">\n");
      out.write("                                                <i class=\"ace-icon fa fa-key\"></i>\n");
      out.write("                                                Retrieve Password\n");
      out.write("                                            </h4>\n");
      out.write("\n");
      out.write("                                            <div class=\"space-6\"></div>\n");
      out.write("                                            <p>\n");
      out.write("                                                Enter your email to receive your information.\n");
      out.write("                                            </p>\n");
      out.write("\n");
      out.write("                                            <form>\n");
      out.write("                                                <fieldset>\n");
      out.write("                                                    <label class=\"block clearfix\">\n");
      out.write("                                                        <span class=\"block input-icon input-icon-right\">\n");
      out.write("                                                            <input type=\"email\" class=\"form-control\" id=\"Retrieveemail\" placeholder=\"Email\" />\n");
      out.write("                                                            <i class=\"ace-icon fa fa-envelope\"></i>\n");
      out.write("                                                        </span>\n");
      out.write("                                                    </label>\n");
      out.write("\n");
      out.write("                                                    <div class=\"clearfix\">\n");
      out.write("                                                        <button type=\"button\" onclick=\"Retrieveemailfunction();\" class=\"width-35 pull-right btn btn-sm btn-danger\">\n");
      out.write("                                                            <i class=\"ace-icon fa fa-lightbulb-o\"></i>\n");
      out.write("                                                            <span class=\"bigger-110\">Send Me!</span>\n");
      out.write("                                                        </button>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </fieldset>\n");
      out.write("                                            </form>\n");
      out.write("                                        </div><!-- /.widget-main -->\n");
      out.write("\n");
      out.write("                                        <div class=\"toolbar center\">\n");
      out.write("                                            <a href=\"#\" data-target=\"#login-box\" class=\"back-to-login-link\">\n");
      out.write("                                                Back to login\n");
      out.write("                                                <i class=\"ace-icon fa fa-arrow-right\"></i>\n");
      out.write("                                            </a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div><!-- /.widget-body -->\n");
      out.write("                                </div><!-- /.forgot-box -->\n");
      out.write("\n");
      out.write("                                <div id=\"signup-box\" class=\"signup-box widget-box no-border\">\n");
      out.write("                                    <div class=\"widget-body\">\n");
      out.write("                                        <div class=\"widget-main\">\n");
      out.write("                                            <h4 class=\"header green lighter bigger\">\n");
      out.write("                                                <i class=\"ace-icon fa fa-users blue\"></i>\n");
      out.write("                                                New User Registration\n");
      out.write("                                            </h4>\n");
      out.write("\n");
      out.write("                                            <div class=\"space-6\"></div>\n");
      out.write("                                            <p id=\"hidesubtitle\"> Enter your details to begin: </p>\n");
      out.write("                                            <p id=\"usernameexist\" style=\"color: red\"> </p>\n");
      out.write("\n");
      out.write("                                            <form>\n");
      out.write("                                                <fieldset>\n");
      out.write("                                                    <label class=\"block clearfix\">\n");
      out.write("                                                        <span class=\"block input-icon input-icon-right\">\n");
      out.write("                                                            <input type=\"text\" class=\"form-control\" id=\"firstName\" placeholder=\"First Name\" />\n");
      out.write("                                                            <i class=\"ace-icon fa fa-user\"></i>\n");
      out.write("                                                        </span>\n");
      out.write("                                                    </label>\n");
      out.write("\n");
      out.write("                                                    <label class=\"block clearfix\">\n");
      out.write("                                                        <span class=\"block input-icon input-icon-right\">\n");
      out.write("                                                            <input type=\"text\" class=\"form-control\" id=\"lastName\" placeholder=\"Last Name\" />\n");
      out.write("                                                            <i class=\"ace-icon fa fa-user\"></i>\n");
      out.write("                                                        </span>\n");
      out.write("                                                    </label>                                                    \n");
      out.write("\n");
      out.write("                                                    <label class=\"block clearfix\">\n");
      out.write("                                                        <span class=\"block input-icon input-icon-right\">\n");
      out.write("                                                            <input type=\"text\" class=\"form-control\" id=\"userNameReg\" placeholder=\"Username\" />\n");
      out.write("                                                            <i class=\"ace-icon fa fa-user\"></i>\n");
      out.write("                                                        </span>\n");
      out.write("                                                    </label>\n");
      out.write("\n");
      out.write("                                                    <label class=\"block clearfix\">\n");
      out.write("                                                        <span class=\"block input-icon input-icon-right\">\n");
      out.write("                                                            <input type=\"email\" class=\"form-control\" id=\"emailReg\" placeholder=\"Email\" />\n");
      out.write("                                                            <i class=\"ace-icon fa fa-envelope\"></i>\n");
      out.write("                                                        </span>\n");
      out.write("                                                    </label>\n");
      out.write("\n");
      out.write("                                                    <label class=\"block clearfix\">\n");
      out.write("                                                        <span class=\"block input-icon input-icon-right\">\n");
      out.write("                                                            <input type=\"email\" class=\"form-control\" id=\"conformemailReg\" placeholder=\"Confirm Email\" />\n");
      out.write("                                                            <i class=\"ace-icon fa fa-envelope\"></i>\n");
      out.write("                                                        </span>\n");
      out.write("                                                    </label>\n");
      out.write("                                                    <!--                                                    <label class=\"block clearfix\">\n");
      out.write("                                                                                                            <span class=\"block input-icon input-icon-right\">\n");
      out.write("                                                                                                                <input type=\"password\" class=\"form-control\" id=\"passWordReg\" placeholder=\"Password\" />\n");
      out.write("                                                                                                                <i class=\"ace-icon fa fa-lock\"></i>\n");
      out.write("                                                                                                            </span>\n");
      out.write("                                                                                                        </label>-->\n");
      out.write("\n");
      out.write("                                                    <!--                                                    <label class=\"block clearfix\">\n");
      out.write("                                                                                                            <span class=\"block input-icon input-icon-right\">\n");
      out.write("                                                                                                                <input type=\"password\" class=\"form-control\" placeholder=\"Repeat password\" />\n");
      out.write("                                                                                                                <i class=\"ace-icon fa fa-retweet\"></i>\n");
      out.write("                                                                                                            </span>\n");
      out.write("                                                                                                        </label>-->\n");
      out.write("\n");
      out.write("                                                    <!--                                                    <label class=\"block\">\n");
      out.write("                                                                                                            <input type=\"checkbox\" class=\"ace\" />\n");
      out.write("                                                                                                            <span class=\"lbl\">\n");
      out.write("                                                                                                                I accept the\n");
      out.write("                                                                                                                <a href=\"#\">User Agreement</a>\n");
      out.write("                                                                                                            </span>\n");
      out.write("                                                                                                        </label>-->\n");
      out.write("\n");
      out.write("                                                    <div class=\"space-24\"></div>\n");
      out.write("\n");
      out.write("                                                    <div class=\"clearfix\">\n");
      out.write("                                                        <button type=\"reset\" class=\"width-30 pull-left btn btn-sm\">\n");
      out.write("                                                            <i class=\"ace-icon fa fa-refresh\"></i>\n");
      out.write("                                                            <span class=\"bigger-110\">Reset</span>\n");
      out.write("                                                        </button>\n");
      out.write("\n");
      out.write("                                                        <button type=\"button\" class=\"width-65 pull-right btn btn-sm btn-success\" onclick=\"createdEngaccount();\">\n");
      out.write("                                                            <span class=\"bigger-110\">Register</span>\n");
      out.write("\n");
      out.write("                                                            <i class=\"ace-icon fa fa-arrow-right icon-on-right\"></i>\n");
      out.write("                                                        </button>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </fieldset>\n");
      out.write("                                            </form>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"toolbar center\">\n");
      out.write("                                            <a href=\"#\" id=\"backlogin\" data-target=\"#login-box\" class=\"back-to-login-link\">\n");
      out.write("                                                <i class=\"ace-icon fa fa-arrow-left\"></i>\n");
      out.write("                                                Back to login\n");
      out.write("                                            </a>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div><!-- /.widget-body -->\n");
      out.write("                                </div><!-- /.signup-box -->\n");
      out.write("                            </div><!-- /.position-relative -->\n");
      out.write("\n");
      out.write("                            <div class=\"navbar-fixed-top align-right\">\n");
      out.write("                                <br />\n");
      out.write("                                &nbsp;\n");
      out.write("                                <a id=\"btn-login-dark\" href=\"#\">Dark</a>\n");
      out.write("                                &nbsp;\n");
      out.write("                                <span class=\"blue\">/</span>\n");
      out.write("                                &nbsp;\n");
      out.write("                                <a id=\"btn-login-blur\" href=\"#\">Blur</a>\n");
      out.write("                                &nbsp;\n");
      out.write("                                <span class=\"blue\">/</span>\n");
      out.write("                                &nbsp;\n");
      out.write("                                <a id=\"btn-login-light\" href=\"#\">Light</a>\n");
      out.write("                                &nbsp; &nbsp; &nbsp;\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div><!-- /.col -->\n");
      out.write("                </div><!-- /.row -->\n");
      out.write("            </div><!-- /.main-content -->\n");
      out.write("        </div><!-- /.main-container -->\n");
      out.write("\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            if ('ontouchstart' in document.documentElement)\n");
      out.write("                document.write(\"<script src='login/components/_mod/jquery.mobile.custom/jquery.mobile.custom.min.js'>\" + \"<\" + \"/script>\");\n");
      out.write("        </script>\n");
      out.write("        <script src=\"login/implementation/loginvalidation.js?1500\"></script>\n");
      out.write("        <!-- inline scripts related to this page -->\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            jQuery(function ($) {\n");
      out.write("                $(document).on('click', '.toolbar a[data-target]', function (e) {\n");
      out.write("                    e.preventDefault();\n");
      out.write("                    var target = $(this).data('target');\n");
      out.write("                    $('.widget-box.visible').removeClass('visible');//hide others\n");
      out.write("                    $(target).addClass('visible');//show target\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("            //you don't need this, just used for changing background\n");
      out.write("            jQuery(function ($) {\n");
      out.write("                $('#btn-login-dark').on('click', function (e) {\n");
      out.write("                    $('body').attr('class', 'login-layout');\n");
      out.write("                    $('#id-text2').attr('class', 'white');\n");
      out.write("                    $('#id-company-text').attr('class', 'blue');\n");
      out.write("                    e.preventDefault();\n");
      out.write("                });\n");
      out.write("                $('#btn-login-light').on('click', function (e) {\n");
      out.write("                    $('body').attr('class', 'login-layout light-login');\n");
      out.write("                    $('#id-text2').attr('class', 'grey');\n");
      out.write("                    $('#id-company-text').attr('class', 'blue');\n");
      out.write("\n");
      out.write("                    e.preventDefault();\n");
      out.write("                });\n");
      out.write("                $('#btn-login-blur').on('click', function (e) {\n");
      out.write("                    $('body').attr('class', 'login-layout blur-login');\n");
      out.write("                    $('#id-text2').attr('class', 'white');\n");
      out.write("                    $('#id-company-text').attr('class', 'light-blue');\n");
      out.write("\n");
      out.write("                    e.preventDefault();\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("        <script>\n");
      out.write("            var validateEmail = function (elementValue) {\n");
      out.write("                var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$/;\n");
      out.write("                return emailPattern.test(elementValue);\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            $('#emailReg').keyup(function () {\n");
      out.write("                var value = $(this).val();\n");
      out.write("                var valid = validateEmail(value);\n");
      out.write("                if (!valid) {\n");
      out.write("                    $(this).css('color', 'red');\n");
      out.write("                } else {\n");
      out.write("                    $(this).css('color', '#000');\n");
      out.write("\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("            $('#conformemailReg').keyup(function () {\n");
      out.write("                var value = $(this).val();\n");
      out.write("                var valid = validateEmail(value);\n");
      out.write("                if (!valid) {\n");
      out.write("                    $(this).css('color', 'red');\n");
      out.write("                } else {\n");
      out.write("                    $(this).css('color', '#000');\n");
      out.write("\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("            $('#Retrieveemail').keyup(function () {\n");
      out.write("                var value = $(this).val();\n");
      out.write("                var valid = validateEmail(value);\n");
      out.write("                if (!valid) {\n");
      out.write("                    $(this).css('color', 'red');\n");
      out.write("                } else {\n");
      out.write("                    $(this).css('color', '#000');\n");
      out.write("\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
