/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2017-03-16 14:02:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/buyer/jsp/site-info.jsp", Long.valueOf(1489672890747L));
    _jspx_dependants.put("/buyer/jsp/content-mainpage.jsp", Long.valueOf(1489672890715L));
    _jspx_dependants.put("/buyer/jsp/header.jsp", Long.valueOf(1489672890729L));
    _jspx_dependants.put("/buyer/jsp/footer.jsp", Long.valueOf(1489672890722L));
    _jspx_dependants.put("/buyer/jsp/searchbar.jsp", Long.valueOf(1489672890736L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <title>Connecting the Unconnected Web site | Home :: On Going Solution</title>\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("        <meta name=\"keywords\" content=\"Connecting the Unconnected Services website, \n");
      out.write("              Bootstrap css spring MVC hibernate web project owner by wprameethmadusanka@gmail.com.\" />\n");
      out.write("        <link rel=\"shortcut icon\" href=\"buyer/assets/img/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("\n");
      out.write("        <link href=\"buyer/assets/css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\"/>        \n");
      out.write("        <link href=\"buyer/assets/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"buyer/assets/css/search-bar.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"buyer/assets/css/templatemo-style.css\" rel=\"stylesheet\" type=\"text/css\"/> \n");
      out.write("        <script src=\"buyer/assets/js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>             \n");
      out.write("        <script src=\"buyer/assets/js/jquery-1.11.2.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"loader-wrapper\">\n");
      out.write("            <div id=\"loader\"></div>\n");
      out.write("            <div class=\"loader-section section-left\"></div>\n");
      out.write("            <div class=\"loader-section section-right\"></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"tm-top-header\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"tm-top-header-inner\">\n");
      out.write("                <div class=\"tm-logo-container\">\n");
      out.write("                    <img src=\"buyer/assets/img/logo5.png\" style=\"width:150px;padding: 0px;margin: 0px;\" alt=\"Logo\" class=\"tm-site-logo\"> <!--error image-->                    \n");
      out.write("                    <!--<h1 class=\"tm-site-name\" style=\"color: yellow\">MyHero </h1>-->\n");
      out.write("                    <!--<h5 style=\"margin: 0px;padding: 0px;\">connecting the unconnected</h5>-->\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mobile-menu-icon\">\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\n");
      out.write("                </div>\n");
      out.write("                <nav class=\"tm-nav\">\n");
      out.write("                    <ul>                                       \n");
      out.write("                        <li ><a href=\"#\" style=\"color: yellow\">Home</a></li>\n");
      out.write("                        <li ><a href=\"#\" style=\"color: yellow\">Services</a></li>\n");
      out.write("                        <li ><a href=\"#\" style=\"color: yellow\">About Us</a></li>\n");
      out.write("                        <li ><a href=\"#\" style=\"color: yellow\">Sign In</a></li>\n");
      out.write("                        <li ><a href=\"#\" style=\"color: yellow\">Sign Up</a></li>\n");
      out.write("                        <li ><a href=\"#\" style=\"color:yellow \">සිංහල</a></li>                        \n");
      out.write("                    </ul>\n");
      out.write("                </nav>                 \n");
      out.write("            </div>           \n");
      out.write("        </div>    \n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("\n");
      out.write("\n");
      out.write("        <div style=\"min-height: 50px;\">         \n");
      out.write("            ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"slider1_container\" class=\"parent\">  \n");
      out.write("    <div style=\"height: 100px;background-color: transparent;position:fixed;width: 100%;z-index:100;\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        <section class=\"tm-welcome-section\" style=\"background-color: transparent;margin-left: 50px;margin-right: 50px;\">\n");
      out.write("            <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\" >\n");
      out.write("            </div>\n");
      out.write("            <div class=\"container tm-position-relative\">\n");
      out.write("                <div class=\"theam-connecting container\">\n");
      out.write("                    <h2 class=\"gold-text tm-welcome-header-2\">\n");
      out.write("                        Connecting the Unconnected\n");
      out.write("                    </h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"jobak-home-search-box\">\n");
      out.write("                    <form method=\"post\" action=\"buyer_second.jsp\" id=\"myForm\">\n");
      out.write("                        <div class=\" \">\n");
      out.write("                            <div class=\"row\">                        \n");
      out.write("                                <div class=\"col-md-2 col-sm-2 \" style=\"padding-right: 0px;color: white;font-size: 20px;font-family: 'Times New Roman', serif;\">\n");
      out.write("                                    I need help with \n");
      out.write("                                </div>                        \n");
      out.write("                                <div class=\"col-md-4 col-sm-4\" style=\"padding-right: 0px;\">\n");
      out.write("                                    <div class=\"form-group\" style=\" position: relative; display: inline-block;width: 100%\">\n");
      out.write("                                        <select class=\"selectpicker form-control myformcontroller\" style=\"color: black;font-weight: bold;\" id=\"allprojectname\">\n");
      out.write("                                        </select>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>                        \n");
      out.write("                                <div class=\"col-md-2 col-sm-2 \" style=\"padding-right: 0px;color: white;font-size: 20px;font-family: 'Times New Roman', serif;\">\n");
      out.write("                                    by finding \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-3 col-sm-3 \" style=\"padding-right: 0px;\">\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("                                        <select id=\"fieldname\" style=\"color: black;font-weight: bold;\" class=\"selectpicker form-control myformcontroller\">                                                                                                                          \n");
      out.write("                                        </select>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-md-1 col-sm-1 \" >\n");
      out.write("                                    <div class=\"form-group\">\n");
      out.write("\n");
      out.write("                                        <div class=\"btn-holder\">\n");
      out.write("                                            <button class=\"btn btn-primary\" style=\"width:50px;padding: 4px !important; font-size:18px;\">\n");
      out.write("                                                <i class=\"glyphicon glyphicon-search\"></i>\n");
      out.write("                                            </button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div> \n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div u=\"loading\" style=\"position: absolute; top: 0px; left: 0px;\">\n");
      out.write("        <div style=\"filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block;\n");
      out.write("             top: 0px; left: 0px; width: 100%; height: 100%;\">\n");
      out.write("        </div>\n");
      out.write("        <div style=\"position: absolute; display: block; background: url(buyer/assets/img/loading.gif) no-repeat center center;\n");
      out.write("             top: 0px; left: 0px; width: 100%; height: 100%;\">\n");
      out.write("        </div>\n");
      out.write("    </div>  \n");
      out.write("\n");
      out.write("    <div u=\"slides\" class=\"child\">\n");
      out.write("        <div class=\"mychild\">\n");
      out.write("            <img u=\"image\" src2=\"buyer/assets/img/1300-620/cc.jpg\" />\n");
      out.write("        </div> \n");
      out.write("        <div class=\"mychild\">\n");
      out.write("            <img u=\"image\" src2=\"buyer/assets/img/1300-620/dd.jpg\" />\n");
      out.write("        </div> \n");
      out.write("        <div class=\"mychild\">\n");
      out.write("            <img u=\"image\" src2=\"buyer/assets/img/1300-620/ee.jpg\"/>\n");
      out.write("        </div> \n");
      out.write("    </div>  \n");
      out.write("\n");
      out.write("    <style>                    \n");
      out.write("        .jssorb21 {\n");
      out.write("            position: absolute;\n");
      out.write("        }\n");
      out.write("        .jssorb21 div, .jssorb21 div:hover, .jssorb21 .av {\n");
      out.write("            position: absolute;\n");
      out.write("            /* size of bullet elment */\n");
      out.write("            width: 19px;\n");
      out.write("            height: 19px;\n");
      out.write("            text-align: center;\n");
      out.write("            line-height: 19px;\n");
      out.write("            color: white;\n");
      out.write("            font-size: 12px;\n");
      out.write("            background: url(buyer/assets/img/b21.png) no-repeat;\n");
      out.write("            overflow: hidden;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        .jssorb21 div { background-position: -5px -5px; }\n");
      out.write("        .jssorb21 div:hover, .jssorb21 .av:hover { background-position: -35px -5px; }\n");
      out.write("        .jssorb21 .av { background-position: -65px -5px; }\n");
      out.write("        .jssorb21 .dn, .jssorb21 .dn:hover { background-position: -95px -5px; }\n");
      out.write("    </style>                \n");
      out.write("    <div u=\"navigator\" class=\"jssorb21\" style=\"bottom: 75px; right: 6px;\">                    \n");
      out.write("        <div u=\"prototype\"></div>\n");
      out.write("    </div>                \n");
      out.write("    <style>                    \n");
      out.write("        .jssora21l, .jssora21r {\n");
      out.write("            display: block;\n");
      out.write("            position: absolute;                        \n");
      out.write("            width: 55px;\n");
      out.write("            height: 55px;\n");
      out.write("            cursor: pointer;\n");
      out.write("            background: url(buyer/assets/img/a21.png) center center no-repeat;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .jssora21l { background-position: -3px -33px; }\n");
      out.write("        .jssora21r { background-position: -63px -33px; }\n");
      out.write("        .jssora21l:hover { background-position: -123px -33px; }\n");
      out.write("        .jssora21r:hover { background-position: -183px -33px; }\n");
      out.write("        .jssora21l.jssora21ldn { background-position: -243px -33px; }\n");
      out.write("        .jssora21r.jssora21rdn { background-position: -303px -33px; }\n");
      out.write("    </style>                  \n");
      out.write("    <span u=\"arrowleft\" class=\"jssora21l\" style=\"top: 123px; left: 8px;\">\n");
      out.write("    </span>                \n");
      out.write("    <span u=\"arrowright\" class=\"jssora21r\" style=\"top: 123px; right: 8px;\">\n");
      out.write("    </span>                               \n");
      out.write("</div>  \n");
      out.write("             \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"tm-main-section light-gray-bg\">\n");
      out.write("            <div class=\"container\" id=\"main\">                \n");
      out.write("                ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<section class=\"tm-section tm-section-margin-bottom-0 row\" id=\"loadindexinfo\">\n");
      out.write("    <div class=\"col-lg-12 tm-section-header-container\" id=\"loadcategoryhr\">\n");
      out.write("        <!--<h2 class=\"tm-section-header\" style=\"color: sienna\">Popular Items</h2>-->\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"col-lg-12 tm-popular-items-container\" id=\"loadcategoryinfo\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"tm-popular-item\">\n");
      out.write("            <img src=\"buyer/assets/img/286-166/1.jpg\" alt=\"Popular\" class=\"tm-popular-item-img\">\n");
      out.write("            <div class=\"tm-popular-item-description\">\n");
      out.write("                <h3 class=\"\">House Work</h3><hr class=\"tm-popular-item-hr\">\n");
      out.write("                <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque. sed ipsum.</p>\n");
      out.write("                <div class=\"order-now-container\">\n");
      out.write("                    <a href=\"#\" class=\"order-now-link\" style=\"padding-top: 25px;font-size: 20px;\">More</a>\n");
      out.write("                </div>\n");
      out.write("            </div>              \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"tm-popular-item\">\n");
      out.write("            <img src=\"buyer/assets/img/286-166/2.jpg\" alt=\"Popular\" class=\"tm-popular-item-img\">\n");
      out.write("            <div class=\"tm-popular-item-description\">\n");
      out.write("                <h3 class=\"\">Construction</h3><hr class=\"tm-popular-item-hr\">\n");
      out.write("                <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque. sed ipsum.</p>\n");
      out.write("                <div class=\"order-now-container\">\n");
      out.write("                    <a href=\"#\" class=\"order-now-link\" style=\"padding-top: 25px;font-size: 20px;\">More</a>\n");
      out.write("                </div>\n");
      out.write("            </div>              \n");
      out.write("        </div>\n");
      out.write("        <div class=\"tm-popular-item\">\n");
      out.write("            <img src=\"buyer/assets/img/286-166/3.jpg\" alt=\"Popular\" class=\"tm-popular-item-img\">\n");
      out.write("            <div class=\"tm-popular-item-description\">\n");
      out.write("                <h3 class=\"\">Education</h3><hr class=\"tm-popular-item-hr\">\n");
      out.write("                <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque. sed ipsum.</p>\n");
      out.write("                <div class=\"order-now-container\">\n");
      out.write("                    <a href=\"#\" class=\"order-now-link\" style=\"padding-top: 25px;font-size: 20px;\">More</a>\n");
      out.write("                </div>\n");
      out.write("            </div>              \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>  \n");
      out.write("    <div id=\"pagination\" style=\"align-items: center\">\n");
      out.write("        <pagination v-ref:table for=\"table\" :per-page=\"PerPage\" :records=\"Records\"></pagination>\n");
      out.write("    </div>\n");
      out.write("</section>");
      out.write("                \n");
      out.write("                ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<section class=\"tm-section\" >\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-lg-12 tm-section-header-container\">\n");
      out.write("            <!--<h2 class=\"tm-section-header\" style=\"color: sienna;\">About Us</h2>--> \n");
      out.write("            <div class=\"tm-hr-container\"><hr class=\"tm-hr\"></div> \n");
      out.write("        </div>  \n");
      out.write("    </div>          \n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"tm-daily-menu-container margin-top-60\">\n");
      out.write("            <div class=\"col-lg-4 col-md-4\">\n");
      out.write("                <img src=\"buyer/assets/img/menu-board.png\" alt=\"Menu board\" class=\"tm-daily-menu-img\">      \n");
      out.write("            </div>            \n");
      out.write("            <div class=\"col-lg-8 col-md-8\">\n");
      out.write("                <p>Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.</p>\n");
      out.write("                <ol class=\"margin-top-30\">\n");
      out.write("                    <li>Tellus eget condimentum rhoncus.</li> \n");
      out.write("                    <li>Sem quam semper libero.</li>\n");
      out.write("                    <li>Sit amet adipiscing sem neque sed ipsum.</li> \n");
      out.write("                    <li>Nam quam nunc, blandit vel, luctus pulvinar.</li> \n");
      out.write("                    <li>Maecenas nec odio et ante tincidunt tempus.</li> \n");
      out.write("                    <li>Donec vitae sapien ut libero ventenatis faucibus.</li> \n");
      out.write("                </ol>\n");
      out.write("                <a href=\"#\" class=\"tm-more-button margin-top-30\">Read More</a>    \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>          \n");
      out.write("</section>");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </div> \n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"tm-black-bg\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row margin-bottom-60\">\n");
      out.write("                <nav class=\"col-lg-3 col-md-3 tm-footer-nav tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>Main Menu</u></h3>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">Home</a></li>\n");
      out.write("                        <li><a href=\"#\">About Us</a></li>\n");
      out.write("                        <li><a href=\"#\">Privacy Policy</a></li>                        \n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <div class=\"col-lg-5 col-md-5 tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>About Us</u></h3>\n");
      out.write("                    <!--<p class=\"margin-top-15\">Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet.</p>-->\n");
      out.write("                    <p class=\"margin-top-15\">\n");
      out.write("                        MyHero (Pvt) Ltd.<br>\n");
      out.write("                        No xx, Xxxxxx,<br>\n");
      out.write("                        Colombo 0x,<br>\n");
      out.write("                        Sri Lanka.<br><br>\n");
      out.write("                        E-mail: info@myhero.com<br>\n");
      out.write("                        Tel No: 091 41 05 172\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>Get Social</u></h3>\n");
      out.write("                    <!--<p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante.</p>-->\n");
      out.write("                    <div class=\"tm-social-icons-container\">\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-linkedin\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-youtube\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-behance\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                    <br>\n");
      out.write("                    <p style=\"font-size: 16px;\"><i class=\"fa fa-android\" aria-hidden=\"true\"></i> <a href=\"\" style=\"color: white\"> Download app for Android.</a></p>\n");
      out.write("                    <p style=\"font-size: 16px;\"><i class=\"fa fa-apple\" aria-hidden=\"true\"></i> <a href=\"\" style=\"color: white\"> Download app for iOS.</a></p>                    \n");
      out.write("                </div>\n");
      out.write("            </div>          \n");
      out.write("        </div>  \n");
      out.write("    </div>      \n");
      out.write("    <div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row tm-copyright\">\n");
      out.write("                <p class=\"col-lg-12 small copyright-text text-center\">Copyright &copy; 2017 MyHero (Pvt)Ltd.</p>\n");
      out.write("            </div>  \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer> ");
      out.write(" \n");
      out.write("\n");
      out.write("        <style>\n");
      out.write("            .jobak-home-search-box .form-group{\n");
      out.write("                margin-bottom:0px;\n");
      out.write("            }\n");
      out.write("            .jobak-home-search-box  {\n");
      out.write("                padding:20px;\n");
      out.write("                background-color: rgba(0,0,0,0.5);\n");
      out.write("                border-bottom: 3px #000000 solid;\n");
      out.write("            }\n");
      out.write("            .VuePagination__count{\n");
      out.write("                display: none;\n");
      out.write("            }\n");
      out.write("        </style> \n");
      out.write("        <script src=\"buyer/assets/js/templatemo-script.js\" type=\"text/javascript\"></script>  \n");
      out.write("        <script src=\"buyer/assets/js/bootstrap.js\" type=\"text/javascript\"></script>        \n");
      out.write("        <script src=\"buyer/assets/js/docs.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"buyer/assets/js/ie10-viewport-bug-workaround.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"buyer/assets/js/jssor.slider.mini.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"buyer/assets/js/sliderjs.js\" type=\"text/javascript\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
