/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2016-12-05 09:15:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <!--IE Compatibility modes-->\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <!--Mobile first-->\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("        <title>Dashboard</title>\n");
      out.write("\n");
      out.write("        <meta name=\"description\" content=\"Free Admin Template Based On Twitter Bootstrap 3.x\">\n");
      out.write("        <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("        <meta name=\"msapplication-TileColor\" content=\"#5bc0de\" />\n");
      out.write("        <meta name=\"msapplication-TileImage\" content=\"assets/img/metis-tile.png\" />\n");
      out.write("\n");
      out.write("        <!-- Bootstrap -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/lib/bootstrap/css/bootstrap.css\">\n");
      out.write("\n");
      out.write("        <!-- Font Awesome -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/lib/font-awesome/css/font-awesome.css\">\n");
      out.write("\n");
      out.write("        <!-- Metis core stylesheet -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/main.css\">\n");
      out.write("\n");
      out.write("        <!-- metisMenu stylesheet -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/lib/metismenu/metisMenu.css\">\n");
      out.write("\n");
      out.write("        <!-- animate.css stylesheet -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/lib/animate.css/animate.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.5/fullcalendar.min.css\">\n");
      out.write("\n");
      out.write("        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("        <!--[if lt IE 9]>\n");
      out.write("            <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("            <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("        <![endif]-->\n");
      out.write("\n");
      out.write("        <!--For Development Only. Not required -->\n");
      out.write("        <script>\n");
      out.write("            less = {\n");
      out.write("                env: \"development\",\n");
      out.write("                relativeUrls: false,\n");
      out.write("                rootpath: \"/assets/\"\n");
      out.write("            };\n");
      out.write("        </script>\n");
      out.write("        <!--<link rel=\"stylesheet\" href=\"assets/css/style-switcher.css\">-->\n");
      out.write("        <link rel=\"stylesheet/less\" type=\"text/css\" href=\"assets/less/theme.less\">\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.1/less.js\"></script>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body class=\"  \">\n");
      out.write("        <div class=\"bg-dark dk\" id=\"wrap\">\n");
      out.write("            <div id=\"top\">\n");
      out.write("                <!-- .navbar -->\n");
      out.write("                <nav class=\"navbar navbar-inverse navbar-static-top\">\n");
      out.write("                    <div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("                        <header class=\"navbar-header\">\n");
      out.write("\n");
      out.write("                            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-ex1-collapse\">\n");
      out.write("                                <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                                <span class=\"icon-bar\"></span>\n");
      out.write("                                <span class=\"icon-bar\"></span>\n");
      out.write("                                <span class=\"icon-bar\"></span>\n");
      out.write("                            </button>\n");
      out.write("                            <a href=\"index.html\" class=\"navbar-brand\"><img src=\"assets/img/logo.png\" alt=\"\"></a>\n");
      out.write("\n");
      out.write("                        </header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"topnav\">\n");
      out.write("                            <div class=\"btn-group\">\n");
      out.write("                                <a data-placement=\"bottom\" data-original-title=\"Fullscreen\" data-toggle=\"tooltip\"\n");
      out.write("                                   class=\"btn btn-default btn-sm\" id=\"toggleFullScreen\">\n");
      out.write("                                    <i class=\"glyphicon glyphicon-fullscreen\"></i>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"btn-group\">\n");
      out.write("                                <a data-placement=\"bottom\" data-original-title=\"E-mail\" data-toggle=\"tooltip\"\n");
      out.write("                                   class=\"btn btn-default btn-sm\">\n");
      out.write("                                    <i class=\"fa fa-envelope\"></i>\n");
      out.write("                                    <span class=\"label label-warning\">5</span>\n");
      out.write("                                </a>\n");
      out.write("                                <a data-placement=\"bottom\" data-original-title=\"Messages\" href=\"#\" data-toggle=\"tooltip\"\n");
      out.write("                                   class=\"btn btn-default btn-sm\">\n");
      out.write("                                    <i class=\"fa fa-comments\"></i>\n");
      out.write("                                    <span class=\"label label-danger\">4</span>\n");
      out.write("                                </a>\n");
      out.write("                                <a data-toggle=\"modal\" data-original-title=\"Help\" data-placement=\"bottom\"\n");
      out.write("                                   class=\"btn btn-default btn-sm\"\n");
      out.write("                                   href=\"#helpModal\">\n");
      out.write("                                    <i class=\"fa fa-question\"></i>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"btn-group\">\n");
      out.write("                                <a href=\"login.html\" data-toggle=\"tooltip\" data-original-title=\"Logout\" data-placement=\"bottom\"\n");
      out.write("                                   class=\"btn btn-metis-1 btn-sm\">\n");
      out.write("                                    <i class=\"fa fa-power-off\"></i>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"btn-group\">\n");
      out.write("                                <a data-placement=\"bottom\" data-original-title=\"Show / Hide Left\" data-toggle=\"tooltip\"\n");
      out.write("                                   class=\"btn btn-primary btn-sm toggle-left\" id=\"menu-toggle\">\n");
      out.write("                                    <i class=\"fa fa-bars\"></i>\n");
      out.write("                                </a>\n");
      out.write("                                <a data-placement=\"bottom\" data-original-title=\"Show / Hide Right\" data-toggle=\"tooltip\"\n");
      out.write("                                   class=\"btn btn-default btn-sm toggle-right\">\n");
      out.write("                                    <span class=\"glyphicon glyphicon-comment\"></span>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <div class=\"collapse navbar-collapse navbar-ex1-collapse\">\n");
      out.write("\n");
      out.write("                            <!-- .nav -->\n");
      out.write("                            <ul class=\"nav navbar-nav\">\n");
      out.write("                                <li class=\"active\"><a href=\"dashboard.html\">Dashboard</a></li>\n");
      out.write("                                <li><a href=\"table.html\">Tables</a></li>\n");
      out.write("                                <li><a href=\"file.html\">File Manager</a></li>\n");
      out.write("                                <li class='dropdown '>\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n");
      out.write("                                        Form Elements <b class=\"caret\"></b>\n");
      out.write("                                    </a>\n");
      out.write("                                    <ul class=\"dropdown-menu\">\n");
      out.write("                                        <li><a href=\"form-general.html\">General</a></li>\n");
      out.write("                                        <li><a href=\"form-validation.html\">Validation</a></li>\n");
      out.write("                                        <li><a href=\"form-wysiwyg.html\">WYSIWYG</a></li>\n");
      out.write("                                        <li><a href=\"form-wizard.html\">Wizard &amp; File Upload</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                            <!-- /.nav -->\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.container-fluid -->\n");
      out.write("                </nav>\n");
      out.write("                <!-- /.navbar -->   \n");
      out.write("                \n");
      out.write("                <!-- /.head -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /#top -->\n");
      out.write("            <div id=\"left\">\n");
      out.write("                <div class=\"media user-media bg-dark dker\">\n");
      out.write("                    <div class=\"user-media-toggleHover\">\n");
      out.write("                        <span class=\"fa fa-user\"></span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"user-wrapper bg-dark\">\n");
      out.write("                        <a class=\"user-link\" href=\"\">\n");
      out.write("                            <img class=\"media-object img-thumbnail user-img\" alt=\"User Picture\" src=\"assets/img/user.gif\">\n");
      out.write("                            <span class=\"label label-danger user-label\">16</span>\n");
      out.write("                        </a>\n");
      out.write("\n");
      out.write("                        <div class=\"media-body\">\n");
      out.write("                            <h5 class=\"media-heading\">Archie</h5>\n");
      out.write("                            <ul class=\"list-unstyled user-info\">\n");
      out.write("                                <li><a href=\"\">Administrator</a></li>\n");
      out.write("                                <li>Last Access : <br>\n");
      out.write("                                    <small><i class=\"fa fa-calendar\"></i>&nbsp;16 Mar 16:32</small>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- #menu -->\n");
      out.write("                <ul id=\"menu\" class=\"bg-blue dker\">\n");
      out.write("                    <li class=\"nav-header\">Menu</li>\n");
      out.write("                    <li class=\"nav-divider\"></li>\n");
      out.write("                    <li class=\"\">\n");
      out.write("                        <a href=\"dashboard.html\">\n");
      out.write("                            <i class=\"fa fa-dashboard\"></i><span class=\"link-title\">&nbsp;Dashboard</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    \n");
      out.write("                    <li class=\"\">\n");
      out.write("                        <a href=\"javascript:;\">\n");
      out.write("                            <i class=\"fa fa-tasks\"></i>\n");
      out.write("                            <span class=\"link-title\">Components</span>\n");
      out.write("                            <span class=\"fa arrow\"></span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"collapse\">\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"bgcolor.html\">\n");
      out.write("                                    <i class=\"fa fa-angle-right\"></i>&nbsp; Bg Color </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"bgimage.html\">\n");
      out.write("                                    <i class=\"fa fa-angle-right\"></i>&nbsp; Bg Image </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"button.html\">\n");
      out.write("                                    <i class=\"fa fa-angle-right\"></i>&nbsp; Buttons </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"icon.html\">\n");
      out.write("                                    <i class=\"fa fa-angle-right\"></i>&nbsp; Icon </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"pricing.html\">\n");
      out.write("                                    <i class=\"fa fa-angle-right\"></i>&nbsp; Pricing Table </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"progress.html\">\n");
      out.write("                                    <i class=\"fa fa-angle-right\"></i>&nbsp; Progress </a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"\">\n");
      out.write("                        <a href=\"javascript:;\">\n");
      out.write("                            <i class=\"fa fa-pencil\"></i>\n");
      out.write("                            <span class=\"link-title\">\n");
      out.write("                                Forms\n");
      out.write("                            </span>\n");
      out.write("                            <span class=\"fa arrow\"></span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"collapse\">\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"form-general.html\">\n");
      out.write("                                    <i class=\"fa fa-angle-right\"></i>&nbsp; Form General </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"form-validation.html\">\n");
      out.write("                                    <i class=\"fa fa-angle-right\"></i>&nbsp; Form Validation </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"form-wizard.html\">\n");
      out.write("                                    <i class=\"fa fa-angle-right\"></i>&nbsp; Form Wizard </a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <a href=\"form-wysiwyg.html\">\n");
      out.write("                                    <i class=\"fa fa-angle-right\"></i>&nbsp; Form WYSIWYG </a>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"table.html\">\n");
      out.write("                            <i class=\"fa fa-table\"></i>\n");
      out.write("                            <span class=\"link-title\">Tables</span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"grid.html\">\n");
      out.write("                            <i class=\"fa fa-columns\"></i>\n");
      out.write("                            <span class=\"link-title\">\n");
      out.write("                                Grid\n");
      out.write("                            </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"blank.html\">\n");
      out.write("                            <i class=\"fa fa-square-o\"></i>\n");
      out.write("                            <span class=\"link-title\">\n");
      out.write("                                Blank Page\n");
      out.write("                            </span>\n");
      out.write("                        </a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-divider\"></li>\n");
      out.write("                    \n");
      out.write("                </ul>\n");
      out.write("                <!-- /#menu -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /#left -->\n");
      out.write("            <div id=\"content\">\n");
      out.write("                <div class=\"outer\">\n");
      out.write("                    <div class=\"inner bg-light lter\">\n");
      out.write("                        <div class=\"text-center\">\n");
      out.write("                            <ul class=\"stats_box\">\n");
      out.write("                                <li>\n");
      out.write("                                    <div class=\"sparkline bar_week\"></div>\n");
      out.write("                                    <div class=\"stat_text\">\n");
      out.write("                                        <strong>2.345</strong>Weekly Visit\n");
      out.write("                                        <span class=\"percent down\"> <i class=\"fa fa-caret-down\"></i> -16%</span>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <div class=\"sparkline line_day\"></div>\n");
      out.write("                                    <div class=\"stat_text\">\n");
      out.write("                                        <strong>165</strong>Daily Visit\n");
      out.write("                                        <span class=\"percent up\"> <i class=\"fa fa-caret-up\"></i> +23%</span>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <div class=\"sparkline pie_week\"></div>\n");
      out.write("                                    <div class=\"stat_text\">\n");
      out.write("                                        <strong>$2 345.00</strong>Weekly Sale\n");
      out.write("                                        <span class=\"percent\"> 0%</span>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("                                    <div class=\"sparkline stacked_month\"></div>\n");
      out.write("                                    <div class=\"stat_text\">\n");
      out.write("                                        <strong>$678.00</strong>Monthly Sale\n");
      out.write("                                        <span class=\"percent down\"> <i class=\"fa fa-caret-down\"></i> -10%</span>\n");
      out.write("                                    </div>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <hr>\n");
      out.write("                        \n");
      out.write("                        <hr>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-lg-8\">\n");
      out.write("                                <div class=\"box\">\n");
      out.write("                                    <header>\n");
      out.write("                                        <h5>Line Chart</h5>\n");
      out.write("                                    </header>\n");
      out.write("                                    <div class=\"body\" id=\"trigo\" style=\"height: 250px;\"></div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-lg-4\">\n");
      out.write("                                <div class=\"box\">\n");
      out.write("                                    <div class=\"body\">\n");
      out.write("                                        <table class=\"table table-condensed table-hovered sortableTable\">\n");
      out.write("                                            <thead>\n");
      out.write("                                                <tr>\n");
      out.write("                                                    <th>Country <i class=\"fa sort\"></i></th>\n");
      out.write("                                                    <th>Visit <i class=\"fa sort\"></i></th>\n");
      out.write("                                                    <th>Time <i class=\"fa sort\"></i></th>\n");
      out.write("                                                </tr>\n");
      out.write("                                            </thead>\n");
      out.write("                                            <tbody>\n");
      out.write("                                                <tr class=\"active\">\n");
      out.write("                                                    <td>Andorra</td>\n");
      out.write("                                                    <td>1126</td>\n");
      out.write("                                                    <td>00:00:15</td>\n");
      out.write("                                                </tr>\n");
      out.write("                                                <tr>\n");
      out.write("                                                    <td>Belarus</td>\n");
      out.write("                                                    <td>350</td>\n");
      out.write("                                                    <td>00:01:20</td>\n");
      out.write("                                                </tr>\n");
      out.write("                                                <tr class=\"danger\">\n");
      out.write("                                                    <td>Paraguay</td>\n");
      out.write("                                                    <td>43</td>\n");
      out.write("                                                    <td>00:00:30</td>\n");
      out.write("                                                </tr>\n");
      out.write("                                                <tr class=\"warning\">\n");
      out.write("                                                    <td>Malta</td>\n");
      out.write("                                                    <td>547</td>\n");
      out.write("                                                    <td>00:10:20</td>\n");
      out.write("                                                </tr>\n");
      out.write("                                                <tr>\n");
      out.write("                                                    <td>Australia</td>\n");
      out.write("                                                    <td>560</td>\n");
      out.write("                                                    <td>00:00:10</td>\n");
      out.write("                                                </tr>\n");
      out.write("                                                <tr>\n");
      out.write("                                                    <td>Kenya</td>\n");
      out.write("                                                    <td>97</td>\n");
      out.write("                                                    <td>00:20:00</td>\n");
      out.write("                                                </tr>\n");
      out.write("                                                <tr class=\"success\">\n");
      out.write("                                                    <td>Italy</td>\n");
      out.write("                                                    <td>2450</td>\n");
      out.write("                                                    <td>00:10:00</td>\n");
      out.write("                                                </tr>\n");
      out.write("                                            </tbody>\n");
      out.write("                                        </table>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <hr>\n");
      out.write("                       \n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.inner -->\n");
      out.write("                </div>\n");
      out.write("                <!-- /.outer -->\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("        <!-- /#wrap -->\n");
      out.write("        <footer class=\"Footer bg-dark dker\">\n");
      out.write("            <p>2016 &copy; Metis Bootstrap Admin Template</p>\n");
      out.write("        </footer>\n");
      out.write("        <!-- /#footer -->\n");
      out.write("        <!-- #helpModal -->\n");
      out.write("        <div id=\"helpModal\" class=\"modal fade\">\n");
      out.write("            <div class=\"modal-dialog\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\n");
      out.write("                        <h4 class=\"modal-title\">Modal title</h4>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        <p>\n");
      out.write("                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore\n");
      out.write("                            et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\n");
      out.write("                            aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\n");
      out.write("                            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in\n");
      out.write("                            culpa qui officia deserunt mollit anim id est laborum.\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-footer\">\n");
      out.write("                        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- /.modal-content -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /.modal-dialog -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.modal -->\n");
      out.write("        <!-- /#helpModal -->\n");
      out.write("        <!--jQuery -->\n");
      out.write("        <script src=\"assets/lib/jquery/jquery.js\"></script>\n");
      out.write("\n");
      out.write("        <script src=\"//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js\"></script>\n");
      out.write("        <script src=\"//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js\"></script>\n");
      out.write("        <script src=\"//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.5/fullcalendar.min.js\"></script>\n");
      out.write("        <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.18.4/js/jquery.tablesorter.min.js\"></script>\n");
      out.write("        <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery-sparklines/2.1.2/jquery.sparkline.min.js\"></script>\n");
      out.write("        <script src=\"//cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.min.js\"></script>\n");
      out.write("        <script src=\"//cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.selection.min.js\"></script>\n");
      out.write("        <script src=\"//cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.resize.min.js\"></script>\n");
      out.write("\n");
      out.write("        <!--Bootstrap -->\n");
      out.write("        <script src=\"assets/lib/bootstrap/js/bootstrap.js\"></script>\n");
      out.write("        <!-- MetisMenu -->\n");
      out.write("        <script src=\"assets/lib/metismenu/metisMenu.js\"></script>\n");
      out.write("        <!-- Screenfull -->\n");
      out.write("        <script src=\"assets/lib/screenfull/screenfull.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Metis core scripts -->\n");
      out.write("        <script src=\"assets/js/core.js\"></script>\n");
      out.write("        <!-- Metis demo scripts -->\n");
      out.write("        <script src=\"assets/js/app.js\"></script>\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            $(function () {\n");
      out.write("                Metis.dashboard();\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("        <!--<script src=\"assets/js/style-switcher.js\"></script>-->\n");
      out.write("        <style>\n");
      out.write("            #menu{\n");
      out.write("                background-color: black !important;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
