/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2017-02-05 01:46:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class buyer_005fregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/buyer/modal/regstation_modal.jsp", Long.valueOf(1486224360107L));
    _jspx_dependants.put("/buyer/jsp/header.jsp", Long.valueOf(1486224360065L));
    _jspx_dependants.put("/buyer/jsp/footer.jsp", Long.valueOf(1486224360057L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>               \n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <title>Cafe House Template</title>\n");
      out.write("\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' rel='stylesheet' type='text/css'>\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Damion' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("        <link href=\"buyer/assets/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"buyer/assets/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("\n");
      out.write("        <link href=\"buyer/assets/css/custom.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("\n");
      out.write("        <link href=\"buyer/assets/css/search-bar.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"buyer/assets/css/templatemo-style.css\" rel=\"stylesheet\" type=\"text/css\"/>        \n");
      out.write("\n");
      out.write("        <link rel=\"shortcut icon\" href=\"buyer/assets/img/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("\n");
      out.write("        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("        <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("        <![endif]-->\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!-- Preloader -->\n");
      out.write("        <div id=\"loader-wrapper\">\n");
      out.write("            <div id=\"loader\"></div>\n");
      out.write("            <div class=\"loader-section section-left\"></div>\n");
      out.write("            <div class=\"loader-section section-right\"></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--header file--> \n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"tm-top-header\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"tm-top-header-inner\">\n");
      out.write("                <div class=\"tm-logo-container\">\n");
      out.write("                    <img src=\"buyer/assets/images/logo5.png\" style=\"width:150px;padding: 0px;margin: 0px;\" alt=\"Logo\" class=\"tm-site-logo\"> <!--error image-->                    \n");
      out.write("                    <!--<h1 class=\"tm-site-name\" style=\"color: yellow\">MyHero </h1>-->\n");
      out.write("                    <!--<h5 style=\"margin: 0px;padding: 0px;\">connecting the unconnected</h5>-->\n");
      out.write("                   \n");
      out.write("                </div>\n");
      out.write("                <div class=\"mobile-menu-icon\">\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\n");
      out.write("                </div>\n");
      out.write("                <nav class=\"tm-nav\">\n");
      out.write("                    <ul>                        \n");
      out.write("                        <li ><a href=\"index.html\">ප්‍රනීත් මදුසංක</a></li>\n");
      out.write("                        <li ><a href=\"index.html\" style=\"color: yellow\">ABOUT US</a></li>                        \n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"javascript:void(0);\" onclick=\"loadSignIn();\" style=\"color: yellow;\">Sign In</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li style=\"padding: 15px;\">\n");
      out.write("                            <select style=\"color: black;margin-left: 20px;\">\n");
      out.write("                                <option value=\"volvo\">English</option>\n");
      out.write("                                <option value=\"volvo\">සිංහල</option>\n");
      out.write("                            </select>                            \n");
      out.write("                        </li>                                                \n");
      out.write("                    </ul>\n");
      out.write("                </nav>                 \n");
      out.write("            </div>           \n");
      out.write("        </div>    \n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("              \n");
      out.write("\n");
      out.write("        <!--content-->\n");
      out.write("        <div class=\"tm-main-section light-gray-bg\">\n");
      out.write("            <div class=\"container\" id=\"main\" >  \n");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Modal -->\n");
      out.write("<div class=\"modal fade\" id=\"reg_modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"loginmodal-container\">\n");
      out.write("            <a href=\"#\" style=\"float: right\" onclick=\"closereg();\"><i class=\"fa fa-close\"></i></a>\n");
      out.write("            <h1>Register an account.</h1><br>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <a href=\"\" class=\"google\" style=\"opacity: 1;color: white;text-align: left;\">\n");
      out.write("                    <i class=\"fa fa-google-plus\"></i>\n");
      out.write("                    Create an account with<strong> Google+</strong>   \n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("                <a href=\"\" class=\"facebook\" style=\"opacity: 1;color: white;text-align: left;\">\n");
      out.write("                    <i class=\"fa fa-facebook\"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("                    Sign in with <strong> Facebook</strong> \n");
      out.write("                </a> \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <a href=\"javascript:void(0);\" style=\"text-align: center;width: 100%;padding: 5px;opacity: 1;padding: 15px;color: black;cursor: default\">OR</a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <input type=\"text\" name=\"user_log\" placeholder=\"Username/Email\" id=\"user_log\">\n");
      out.write("                <input type=\"password\" name=\"pass_log\" placeholder=\"Password\" id=\"pass_log\">\n");
      out.write("                <input type=\"password\" name=\"pass_log\" placeholder=\"Password repeat\" id=\"pass_log\">\n");
      out.write("                <div>\n");
      out.write("                    <a href=\"#\" style=\"text-align: center;width: 100%;padding: 0px;margin: 0px;opacity: 1;padding: 15px;color: black;cursor: pointer\">\n");
      out.write("                        <input type=\"checkbox\"/> I agree to the Terms\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <input type=\"submit\" name=\"login_log\" class=\"login loginmodal-submit\" value=\"Register\" style=\"margin-bottom: 0px;\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("             <div class=\"login-help\" style=\"padding-top: 10px;\">                \n");
      out.write("                <a href=\"#\" onclick=\"loadSignIn();\" style=\"float: right;color: black;opacity: 1;\">Sign in page</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div> \n");
      out.write("\n");
      out.write("        <!-- Footer content-->\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"tm-black-bg\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row margin-bottom-60\">\n");
      out.write("                <nav class=\"col-lg-3 col-md-3 tm-footer-nav tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>Main Menu</u></h3>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">Home</a></li>\n");
      out.write("                        <li><a href=\"#\">About Us</a></li>\n");
      out.write("                        <li><a href=\"#\">Privacy Policy</a></li>                        \n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <div class=\"col-lg-5 col-md-5 tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>About Us</u></h3>\n");
      out.write("                    <!--<p class=\"margin-top-15\">Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet.</p>-->\n");
      out.write("                    <p class=\"margin-top-15\">\n");
      out.write("                        MyHero (Pvt) Ltd.<br>\n");
      out.write("                        No xx, Xxxxxx,<br>\n");
      out.write("                        Colombo 0x,<br>\n");
      out.write("                        Sri Lanka.<br><br>\n");
      out.write("                        E-mail: info@myhero.com<br>\n");
      out.write("                        Tel No: 091 41 05 172\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>Get Social</u></h3>\n");
      out.write("                    <!--<p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante.</p>-->\n");
      out.write("                    <div class=\"tm-social-icons-container\">\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-linkedin\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-youtube\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-behance\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                    <br>\n");
      out.write("                    <p style=\"font-size: 16px;\"><i class=\"fa fa-android\" aria-hidden=\"true\"></i> <a href=\"\" style=\"color: white\"> Download app for Android.</a></p>\n");
      out.write("                    <p style=\"font-size: 16px;\"><i class=\"fa fa-apple\" aria-hidden=\"true\"></i> <a href=\"\" style=\"color: white\"> Download app for iOS.</a></p>                    \n");
      out.write("                </div>\n");
      out.write("            </div>          \n");
      out.write("        </div>  \n");
      out.write("    </div>      \n");
      out.write("    <div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row tm-copyright\">\n");
      out.write("                <p class=\"col-lg-12 small copyright-text text-center\">Copyright &copy; 2017 MyHero (Pvt)Ltd.</p>\n");
      out.write("            </div>  \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer> ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- jQuery -->\n");
      out.write("        <script src=\"buyer/assets/js/jquery-1.11.2.min.js\" type=\"text/javascript\"></script>            \n");
      out.write("        <!-- Templatemo Script -->\n");
      out.write("        <script src=\"buyer/assets/js/templatemo-script.js\" type=\"text/javascript\"></script>                 \n");
      out.write("        <script src=\"buyer/assets/js/custom.js\" type=\"text/javascript\"></script>\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            $(\"#myslide > div:gt(0)\").hide();\n");
      out.write("\n");
      out.write("            setInterval(function () {\n");
      out.write("                $('#myslide > div:first')\n");
      out.write("                        .fadeOut(1000)\n");
      out.write("                        .next()\n");
      out.write("                        .fadeIn(1000)\n");
      out.write("                        .end()\n");
      out.write("                        .appendTo('#myslide');\n");
      out.write("            }, 3000);\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
