/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2017-02-05 01:46:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class buyer_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/buyer/modal/regstation_modal.jsp", Long.valueOf(1486224360107L));
    _jspx_dependants.put("/buyer/jsp/site-info.jsp", Long.valueOf(1486224360092L));
    _jspx_dependants.put("/buyer/jsp/searchbar-with-sliderimage.jsp", Long.valueOf(1486224360086L));
    _jspx_dependants.put("/buyer/jsp/content-mainpage.jsp", Long.valueOf(1486224360050L));
    _jspx_dependants.put("/buyer/jsp/header.jsp", Long.valueOf(1486224360065L));
    _jspx_dependants.put("/buyer/jsp/footer.jsp", Long.valueOf(1486224360057L));
    _jspx_dependants.put("/buyer/modal/login_modal.jsp", Long.valueOf(1486224360100L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <title>Cafe House Template</title>\n");
      out.write("\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' rel='stylesheet' type='text/css'>\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Damion' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("        <link href=\"buyer/assets/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"buyer/assets/css/search-bar.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <link href=\"buyer/assets/css/templatemo-style.css\" rel=\"stylesheet\" type=\"text/css\"/>        \n");
      out.write("        <link rel=\"shortcut icon\" href=\"buyer/assets/img/favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("\n");
      out.write("        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("        <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("        <![endif]-->\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Modal -->\n");
      out.write("<div class=\"modal fade\" id=\"login_modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"loginmodal-container\">\n");
      out.write("            <a href=\"#\" style=\"float: right\" onclick=\"closelog();\"><i class=\"fa fa-close\"></i></a>\n");
      out.write("            <h1>Login to Your Account</h1><br>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <a href=\"\" class=\"google\" style=\"opacity: 1;color: white;text-align: left;\">\n");
      out.write("                    <i class=\"fa fa-google-plus\"></i>\n");
      out.write("                    Create an account with<strong> Google+</strong>   \n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("                <a href=\"\" class=\"facebook\" style=\"opacity: 1;color: white;text-align: left;\">\n");
      out.write("                    <i class=\"fa fa-facebook\"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("                    Sign in with <strong> Facebook</strong> \n");
      out.write("                </a> \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <a href=\"javascript:void(0);\" style=\"text-align: center;width: 100%;padding: 5px;opacity: 1;padding: 15px;color: black;cursor: default\">OR</a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <input type=\"text\" name=\"user_log\" placeholder=\"Username\" id=\"user_log\">\n");
      out.write("                <input type=\"password\" name=\"pass_log\" placeholder=\"Password\" id=\"pass_log\">\n");
      out.write("                <div>\n");
      out.write("                    <a href=\"javascript:void(0);\" style=\"text-align: center;width: 100%;padding: 0px;margin: 0px;opacity: 1;padding: 15px;color: black;cursor: default\">\n");
      out.write("                        <input type=\"checkbox\"/> Remember me\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <input type=\"submit\" name=\"login_log\" class=\"login loginmodal-submit\" value=\"Login\" style=\"margin-bottom: 0px;\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div class=\"login-help\" style=\"padding-top: 10px;\">\n");
      out.write("                <a href=\"#\" onclick=\"reg_modal();\" style=\"float: left;color: black;opacity: 1;\">Register</a>\n");
      out.write("                <a href=\"#\" style=\"float: right;color: black;opacity: 1;\">Forgot Password</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Modal -->\n");
      out.write("<div class=\"modal fade\" id=\"reg_modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"loginmodal-container\">\n");
      out.write("            <a href=\"#\" style=\"float: right\" onclick=\"closereg();\"><i class=\"fa fa-close\"></i></a>\n");
      out.write("            <h1>Register an account.</h1><br>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <a href=\"\" class=\"google\" style=\"opacity: 1;color: white;text-align: left;\">\n");
      out.write("                    <i class=\"fa fa-google-plus\"></i>\n");
      out.write("                    Create an account with<strong> Google+</strong>   \n");
      out.write("                </a>\n");
      out.write("\n");
      out.write("                <a href=\"\" class=\"facebook\" style=\"opacity: 1;color: white;text-align: left;\">\n");
      out.write("                    <i class=\"fa fa-facebook\"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("                    Sign in with <strong> Facebook</strong> \n");
      out.write("                </a> \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <a href=\"javascript:void(0);\" style=\"text-align: center;width: 100%;padding: 5px;opacity: 1;padding: 15px;color: black;cursor: default\">OR</a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <input type=\"text\" name=\"user_log\" placeholder=\"Username/Email\" id=\"user_log\">\n");
      out.write("                <input type=\"password\" name=\"pass_log\" placeholder=\"Password\" id=\"pass_log\">\n");
      out.write("                <input type=\"password\" name=\"pass_log\" placeholder=\"Password repeat\" id=\"pass_log\">\n");
      out.write("                <div>\n");
      out.write("                    <a href=\"#\" style=\"text-align: center;width: 100%;padding: 0px;margin: 0px;opacity: 1;padding: 15px;color: black;cursor: pointer\">\n");
      out.write("                        <input type=\"checkbox\"/> I agree to the Terms\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <input type=\"submit\" name=\"login_log\" class=\"login loginmodal-submit\" value=\"Register\" style=\"margin-bottom: 0px;\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("             <div class=\"login-help\" style=\"padding-top: 10px;\">                \n");
      out.write("                <a href=\"#\" onclick=\"loadSignIn();\" style=\"float: right;color: black;opacity: 1;\">Sign in page</a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Preloader -->\n");
      out.write("        <div id=\"loader-wrapper\">\n");
      out.write("            <div id=\"loader\"></div>\n");
      out.write("            <div class=\"loader-section section-left\"></div>\n");
      out.write("            <div class=\"loader-section section-right\"></div>\n");
      out.write("        </div>\n");
      out.write("        <!-- End Preloader -->\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"tm-top-header\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"tm-top-header-inner\">\n");
      out.write("                <div class=\"tm-logo-container\">\n");
      out.write("                    <img src=\"buyer/assets/images/logo5.png\" style=\"width:150px;padding: 0px;margin: 0px;\" alt=\"Logo\" class=\"tm-site-logo\"> <!--error image-->                    \n");
      out.write("                    <!--<h1 class=\"tm-site-name\" style=\"color: yellow\">MyHero </h1>-->\n");
      out.write("                    <!--<h5 style=\"margin: 0px;padding: 0px;\">connecting the unconnected</h5>-->\n");
      out.write("                   \n");
      out.write("                </div>\n");
      out.write("                <div class=\"mobile-menu-icon\">\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\n");
      out.write("                </div>\n");
      out.write("                <nav class=\"tm-nav\">\n");
      out.write("                    <ul>                        \n");
      out.write("                        <li ><a href=\"index.html\">ප්‍රනීත් මදුසංක</a></li>\n");
      out.write("                        <li ><a href=\"index.html\" style=\"color: yellow\">ABOUT US</a></li>                        \n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"javascript:void(0);\" onclick=\"loadSignIn();\" style=\"color: yellow;\">Sign In</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li style=\"padding: 15px;\">\n");
      out.write("                            <select style=\"color: black;margin-left: 20px;\">\n");
      out.write("                                <option value=\"volvo\">English</option>\n");
      out.write("                                <option value=\"volvo\">සිංහල</option>\n");
      out.write("                            </select>                            \n");
      out.write("                        </li>                                                \n");
      out.write("                    </ul>\n");
      out.write("                </nav>                 \n");
      out.write("            </div>           \n");
      out.write("        </div>    \n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("           <!--header file-->\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<section class=\"tm-welcome-section\">\n");
      out.write("\n");
      out.write("    <div class=\"container tm-position-relative\">\n");
      out.write("\n");
      out.write("        <div class=\"theam-connecting container\">\n");
      out.write("            <h2 class=\"gold-text tm-welcome-header-2\">\n");
      out.write("                Connecting the Unconnected\n");
      out.write("            </h2>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!--        <div class=\"row tm-welcome-content\">            \n");
      out.write("                    <div class=\"search_list\">\n");
      out.write("                        <input type=\"text\" value=\"Search for Services Categories\"/>\n");
      out.write("                        <a href=\"\"><i class=\"fa fa-angle-double-down\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                    <div style=\"float: right;\" class=\"search_location\">\n");
      out.write("                        <input type=\"text\" value=\"Current Location\"/>\n");
      out.write("                        <a href=\"\"><i class=\"fa fa-angle-double-down\"></i></a>\n");
      out.write("                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n");
      out.write("                        <input class=\"button_submit\" type=\"button\"/>\n");
      out.write("                        <a href=\"\" style=\"font-size: 20px;\"><i class=\"fa fa-search\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div> -->\n");
      out.write("\n");
      out.write("        <div class=\"jobak-home-search-box\">\n");
      out.write("\n");
      out.write("            <form method=\"post\" action=\"http://jobak.lk/jobs/brows_jobs\">\n");
      out.write("                <div class=\" \">\n");
      out.write("                    <div class=\"row\">                        \n");
      out.write("                        <div class=\"col-md-2 col-sm-2 \" style=\"padding-right: 0px;color: white;font-size: 20px;font-family: 'Times New Roman', serif;\">\n");
      out.write("                            I need help with \n");
      out.write("                        </div>                        \n");
      out.write("                        <div class=\"col-md-4 col-sm-4 \" style=\"padding-right: 0px;\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("                                <select name=\"ex_category\" id=\"ex_category\"  class=\"selectpicker form-control\" data-show-subtext=\"true\" data-live-search=\"true\">\n");
      out.write("                                    <option value=\"-1\">Select your field</option>\n");
      out.write("                                    <option value=\"9\">Information & Communication Technology</option><option value=\"22\">Marketing & Communications</option><option value=\"2\">Administration & Office Support</option><option value=\"26\">Sales</option><option value=\"11\">Call Centre & Customer Service</option><option value=\"1\">Accounting</option><option value=\"6\">Design & Architecture</option><option value=\"15\">Engineering</option><option value=\"19\">Human Resources & Recruitment</option><option value=\"40\">Data Entry Operator</option><option value=\"10\">Manufacturing, Transport & Logistics</option><option value=\"39\">Quantity Surveyor</option><option value=\"41\">Analyst</option><option value=\"5\">Construction</option><option value=\"18\">Hospitality & Tourism</option><option value=\"8\">Healthcare & Medical</option><option value=\"20\">Insurance & Superannuation</option><option value=\"38\">Finance </option><option value=\"37\">Banking</option><option value=\"42\">Driver</option><option value=\"3\">Advertising & Media</option><option value=\"7\">Education & Training</option><option value=\"33\">Multiple Jobs</option><option value=\"29\">Sport & Recreation</option><option value=\"28\">Self Employment</option><option value=\"27\">Science & Technology</option><option value=\"25\">Retail & Consumer Products</option><option value=\"24\">Real Estate & Property</option><option value=\"35\">Apparel And Textile</option><option value=\"16\">Farming, Animals & Conservation</option><option value=\"23\">Mining, Resources & Energy</option><option value=\"31\">BPO/KPO</option><option value=\"21\">Legal</option><option value=\"12\">CEO & General Management</option><option value=\"13\">Community Services & Development</option><option value=\"14\">Consulting & Strategy</option><option value=\"36\">Counselling </option><option value=\"17\">Government & Defence</option><option value=\"30\">Trades & Services</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                        </div>                        \n");
      out.write("                        <div class=\"col-md-2 col-sm-2 \" style=\"padding-right: 0px;color: white;font-size: 20px;font-family: 'Times New Roman', serif;\">\n");
      out.write("                            by finding \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-3 col-sm-3 \" style=\"padding-right: 0px;\">\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("\n");
      out.write("                                <select name=\"ex_location\" id=\"ex_location\"   class=\"selectpicker form-control\" data-show-subtext=\"true\" data-live-search=\"true\">\n");
      out.write("                                    <option value=\"-1\">Select your location</option>\n");
      out.write("                                    <option value=\"30\">Ampara</option><option value=\"6\">Anuradhapura</option><option value=\"7\">Badulla</option><option value=\"19\">Batticaloa</option><option value=\"2\">Colombo</option><option value=\"10\">Galle</option><option value=\"3\">Gampaha</option><option value=\"11\">Hambantota</option><option value=\"16\">Jaffna</option><option value=\"26\">Kalutara</option><option value=\"4\">Kandy</option><option value=\"28\">Kegalle</option><option value=\"15\">Kilinochchi</option><option value=\"21\">Kurunegala</option><option value=\"17\">Mannar</option><option value=\"27\">Matale</option><option value=\"5\">Matara</option><option value=\"13\">Monaragala</option><option value=\"23\">Mullaitivu</option><option value=\"14\">Nuwara Eliya</option><option value=\"22\">Polonnaruwa</option><option value=\"25\">Puttalam</option><option value=\"29\">Ratnapura</option><option value=\"18\">Trincomalee</option><option value=\"24\">Vavuniya</option>                                                        \n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-1 col-sm-1 \" >\n");
      out.write("                            <div class=\"form-group\">\n");
      out.write("\n");
      out.write("                                <div class=\"btn-holder\">\n");
      out.write("                                    <button class=\"btn btn-primary\" style=\"width:50px;padding: 4px !important; font-size:18px;\">\n");
      out.write("                                        <i class=\"glyphicon glyphicon-search\"></i>\n");
      out.write("                                    </button>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div> \n");
      out.write("</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"tm-main-section light-gray-bg\">\n");
      out.write("            <div class=\"container\" id=\"main\">\n");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("\n");
      out.write("<section class=\"tm-section tm-section-margin-bottom-0 row\">\n");
      out.write("    <div class=\"col-lg-12 tm-section-header-container\">\n");
      out.write("        <h2 class=\"tm-section-header\" style=\"color: sienna\">Popular Items</h2>\n");
      out.write("        <div class=\"tm-hr-container\"><hr class=\"tm-hr\"></div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"col-lg-12 tm-popular-items-container\">\n");
      out.write("        <div class=\"tm-popular-item\">\n");
      out.write("            <img src=\"buyer/assets/img/popular-1.jpg\" alt=\"Popular\" class=\"tm-popular-item-img\">\n");
      out.write("            <div class=\"tm-popular-item-description\">\n");
      out.write("                <h3 class=\"\">House Work</h3><hr class=\"tm-popular-item-hr\">\n");
      out.write("                <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque. sed ipsum.</p>\n");
      out.write("                <div class=\"order-now-container\">\n");
      out.write("                    <a href=\"#\" class=\"order-now-link\" style=\"padding-top: 25px;font-size: 20px;\">More</a>\n");
      out.write("                </div>\n");
      out.write("            </div>              \n");
      out.write("        </div>\n");
      out.write("        <div class=\"tm-popular-item\">\n");
      out.write("            <img src=\"buyer/assets/img/popular-2.jpg\" alt=\"Popular\" class=\"tm-popular-item-img\">\n");
      out.write("            <div class=\"tm-popular-item-description\">\n");
      out.write("                <h3 class=\"\">Construction</h3><hr class=\"tm-popular-item-hr\">\n");
      out.write("                <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque. sed ipsum.</p>\n");
      out.write("                <div class=\"order-now-container\">\n");
      out.write("                    <a href=\"#\" class=\"order-now-link\" style=\"padding-top: 25px;font-size: 20px;\">More</a>\n");
      out.write("                </div>\n");
      out.write("            </div>              \n");
      out.write("        </div>\n");
      out.write("        <div class=\"tm-popular-item\">\n");
      out.write("            <img src=\"buyer/assets/img/popular-3.jpg\" alt=\"Popular\" class=\"tm-popular-item-img\">\n");
      out.write("            <div class=\"tm-popular-item-description\">\n");
      out.write("                <h3 class=\"\">Education</h3><hr class=\"tm-popular-item-hr\">\n");
      out.write("                <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque. sed ipsum.</p>\n");
      out.write("                <div class=\"order-now-container\">\n");
      out.write("                    <a href=\"#\" class=\"order-now-link\" style=\"padding-top: 25px;font-size: 20px;\">More</a>\n");
      out.write("                </div>\n");
      out.write("            </div>              \n");
      out.write("        </div>\n");
      out.write("    </div>          \n");
      out.write("</section>");
      out.write("\n");
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("\n");
      out.write("<section class=\"tm-section\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"col-lg-12 tm-section-header-container\">\n");
      out.write("            <h2 class=\"tm-section-header\" style=\"color: sienna;\">About Us</h2> \n");
      out.write("            <div class=\"tm-hr-container\"><hr class=\"tm-hr\"></div> \n");
      out.write("        </div>  \n");
      out.write("    </div>          \n");
      out.write("    <div class=\"row\">\n");
      out.write("        <div class=\"tm-daily-menu-container margin-top-60\">\n");
      out.write("            <div class=\"col-lg-4 col-md-4\">\n");
      out.write("                <img src=\"buyer/assets/img/menu-board.png\" alt=\"Menu board\" class=\"tm-daily-menu-img\">      \n");
      out.write("            </div>            \n");
      out.write("            <div class=\"col-lg-8 col-md-8\">\n");
      out.write("                <p>Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.</p>\n");
      out.write("                <ol class=\"margin-top-30\">\n");
      out.write("                    <li>Tellus eget condimentum rhoncus.</li> \n");
      out.write("                    <li>Sem quam semper libero.</li>\n");
      out.write("                    <li>Sit amet adipiscing sem neque sed ipsum.</li> \n");
      out.write("                    <li>Nam quam nunc, blandit vel, luctus pulvinar.</li> \n");
      out.write("                    <li>Maecenas nec odio et ante tincidunt tempus.</li> \n");
      out.write("                    <li>Donec vitae sapien ut libero ventenatis faucibus.</li> \n");
      out.write("                </ol>\n");
      out.write("                <a href=\"#\" class=\"tm-more-button margin-top-30\">Read More</a>    \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>          \n");
      out.write("</section>");
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div> \n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"tm-black-bg\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row margin-bottom-60\">\n");
      out.write("                <nav class=\"col-lg-3 col-md-3 tm-footer-nav tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>Main Menu</u></h3>\n");
      out.write("                    <ul>\n");
      out.write("                        <li><a href=\"#\">Home</a></li>\n");
      out.write("                        <li><a href=\"#\">About Us</a></li>\n");
      out.write("                        <li><a href=\"#\">Privacy Policy</a></li>                        \n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <div class=\"col-lg-5 col-md-5 tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>About Us</u></h3>\n");
      out.write("                    <!--<p class=\"margin-top-15\">Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet.</p>-->\n");
      out.write("                    <p class=\"margin-top-15\">\n");
      out.write("                        MyHero (Pvt) Ltd.<br>\n");
      out.write("                        No xx, Xxxxxx,<br>\n");
      out.write("                        Colombo 0x,<br>\n");
      out.write("                        Sri Lanka.<br><br>\n");
      out.write("                        E-mail: info@myhero.com<br>\n");
      out.write("                        Tel No: 091 41 05 172\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-lg-4 col-md-4 tm-footer-div\">\n");
      out.write("                    <h3 class=\"tm-footer-div-title\"><u>Get Social</u></h3>\n");
      out.write("                    <!--<p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante.</p>-->\n");
      out.write("                    <div class=\"tm-social-icons-container\">\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-linkedin\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-youtube\"></i></a>\n");
      out.write("                        <a href=\"#\" class=\"tm-social-icon\"><i class=\"fa fa-behance\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                    <br>\n");
      out.write("                    <p style=\"font-size: 16px;\"><i class=\"fa fa-android\" aria-hidden=\"true\"></i> <a href=\"\" style=\"color: white\"> Download app for Android.</a></p>\n");
      out.write("                    <p style=\"font-size: 16px;\"><i class=\"fa fa-apple\" aria-hidden=\"true\"></i> <a href=\"\" style=\"color: white\"> Download app for iOS.</a></p>                    \n");
      out.write("                </div>\n");
      out.write("            </div>          \n");
      out.write("        </div>  \n");
      out.write("    </div>      \n");
      out.write("    <div>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row tm-copyright\">\n");
      out.write("                <p class=\"col-lg-12 small copyright-text text-center\">Copyright &copy; 2017 MyHero (Pvt)Ltd.</p>\n");
      out.write("            </div>  \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer> ");
      out.write("           <!-- Footer content-->\n");
      out.write("\n");
      out.write("        <!-- JS -->\n");
      out.write("        <script src=\"buyer/assets/js/jquery-1.11.2.min.js\" type=\"text/javascript\"></script>         <!-- jQuery -->        \n");
      out.write("        <script src=\"buyer/assets/js/templatemo-script.js\" type=\"text/javascript\"></script>         <!-- Templatemo Script -->\n");
      out.write("        <script type=\"text/javascript\" src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>    \n");
      out.write("\n");
      out.write("        <script src=\"buyer/implimentation/loadjs.js\"></script>\n");
      out.write("        <style>\n");
      out.write("            .jobak-home-search-box .form-group{\n");
      out.write("                margin-bottom:0px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("            .jobak-home-search-box  {\n");
      out.write("\n");
      out.write("\n");
      out.write("                padding:20px;\n");
      out.write("                background-color: rgba(0,0,0,0.5);\n");
      out.write("                border-bottom: 3px #000000 solid;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
